"""Akida SNN script generator.

Translates verified NeuroCNL IR to a native Python script that
uses the `akida` package.
"""

import sys
import warnings

from neurocnl.ir.types import NetworkIR
from neurocnl.mapping.akida_mapper import map_network_ir_to_akida_representation


def generate_script(ir_model: NetworkIR) -> str:
    """Generate executable scaffolding for native Akida SNN APIs.

    Parameters
    ----------
    ir_model : NetworkIR
        The fully lowered and validated NeuroCNL Intermediate Representation.

    Returns
    -------
    str
        Python script string invoking `akida.Sequential()` natively.

    Raises
    ------
    RuntimeError
        If an unsupported feature or fatal capability flag is present.
    """
    if sys.platform == "darwin":
        warnings.warn(
            "Brainchip's Akida Python tools currently do not support macOS. "
            "Execution of the generated script may fail on this platform.",
            RuntimeWarning,
            stacklevel=2,
        )

    mapped = map_network_ir_to_akida_representation(ir_model)

    lines = [
        '"""Akida SNN deployment script — auto-generated by neurocnl."""',
        "",
        "import numpy as np",
        "import akida",
        "from akida import FullyConnected, Input",
        "",
        "def create_model() -> akida.Model:",
        "    model = akida.Sequential()",
    ]

    # Map IR populations and connections to Akida Sequential logic.
    # Note: akida.Sequential expects a strict, feedforward layer chain.
    # We will build a single input layer (for the first population/source)
    # and map subsequent connections to FullyConnected layers.

    if not mapped.populations:
        lines.append("    # Warning: No populations defined in IR.")
        lines.append("    return model")
        lines.append("")
        lines.append("if __name__ == '__main__':")
        lines.append("    model = create_model()")
        lines.append("    model.summary()")
        return "\n".join(lines)

    # In a fully sequential mapping, the first population is the Input.
    first_population = mapped.populations[0]
    first_pop = first_population.id
    in_size = first_population.size
    lines.append(f"    # Input Population: {first_pop}")
    lines.append(f"    model.add(Input(input_shape=({in_size},)))")

    for connection in mapped.connections:
        lines.append(f"    # Connection: {connection.source} -> {connection.target}")
        if connection.block_type is not None:
            lines.append(f"    # Akida block type: {connection.block_type}")
        lines.append(
            f"    model.add(FullyConnected(units={connection.units}, name='{connection.target}'))"
        )

    lines.extend(
        [
            "",
            "    return model",
            "",
            "if __name__ == '__main__':",
            "    model = create_model()",
            "    model.summary()",
            "    # Note: Use model.forward(inputs) for inference.",
        ]
    )

    return "\n".join(lines)
