#!/usr/bin/env bash
# scripts/gen_secrets.sh
# Generates Neurohub's production secrets and writes them to .env.prod.
# Run once before first deploy: bash scripts/gen_secrets.sh
# Review .env.prod, fill in GITHUB_OAUTH_CLIENT_ID, then load into Secret Manager.
set -euo pipefail

ENV_FILE=".env.prod"

if [[ -f "$ENV_FILE" ]]; then
  echo "⚠️  $ENV_FILE already exists. Delete it first to regenerate secrets."
  exit 1
fi

echo "Generating Neurohub production secrets..."

gen() { python3 -c "import secrets; print(secrets.token_hex(32))"; }

NEUROHUB_SECRET_KEY=$(gen)
JWT_SECRET=$(gen)

cat > "$ENV_FILE" <<EOF
# ─── Generated by scripts/gen_secrets.sh on $(date -u +"%Y-%m-%dT%H:%MZ") ───────────────
# NEVER commit this file. Add .env.prod to .gitignore.

# ── GitHub OAuth Device Flow (Client ID is public, not a secret — see the
#    Neurohub GitHub migration plan for why) ─────────────────────────────────
GITHUB_OAUTH_CLIENT_ID=REPLACE_WITH_GITHUB_OAUTH_APP_CLIENT_ID

# ── Internal JWT auth for the legacy /api/neurohub and /api/v1 routes this
#    service still carries — unrelated to GitHub sign-in, required to boot ──
NEUROHUB_SECRET_KEY=${NEUROHUB_SECRET_KEY}
JWT_SECRET=${JWT_SECRET}
NEUROHUB_AUTH_ENABLED=true
ENVIRONMENT=production

# ── CORS ───────────────────────────────────────────────────────────────────
ALLOWED_ORIGINS=*

# No database, object storage, cache, or search index to configure —
# Neurohub holds no application data of its own; GitHub is the only
# persistence layer, and everything else degrades gracefully when unset.
EOF

chmod 600 "$ENV_FILE"

echo ""
echo "✅ Secrets written to $ENV_FILE"
echo ""
echo "Next steps:"
echo "  1. Fill in GITHUB_OAUTH_CLIENT_ID in $ENV_FILE"
echo "  2. Load each secret into GCP Secret Manager:"
echo "     gcloud secrets create neurohub-secret-key --data-file=- <<< \"\${NEUROHUB_SECRET_KEY}\""
echo "     gcloud secrets create neurohub-jwt-secret --data-file=- <<< \"\${JWT_SECRET}\""
echo "  3. Deploy: bash scripts/deploy.sh"
