"""Emit main.c / snn_data.h for a feedforward LIF network from snn-mlir layer info.

The `snn-mlir` pip package's C-runtime generator (`examples/_codegen.py`) is not
part of the published package, so this reimplements that step against the
package's documented low-level API (`snn_mlir.parse_graph`).

NodeInfo attribute names below (name/size/weights/bias/threshold) are inferred
from the package's public surface, not verified against an installed copy —
confirm these against the real `snn_mlir.parse_graph()` output during Phase 3
integration testing and adjust if the actual field names differ.
"""

from dataclasses import dataclass


@dataclass
class CArtifacts:
    main_c: str
    snn_data_h: str


def _layer_size(layer: object) -> int:
    return int(getattr(layer, "size", 0))


def _layer_weights(layer: object) -> list[list[float]] | None:
    return getattr(layer, "weights", None)


def _layer_threshold(layer: object) -> float:
    return float(getattr(layer, "threshold", 1.0))


def emit_snn_data_h(layers: list[object]) -> str:
    """Emit layer size constants and baked-in weight arrays."""
    lines = [
        "/* Auto-generated by workers/snn_mlir_compiler/codegen.py — do not edit. */",
        "#ifndef SNN_DATA_H",
        "#define SNN_DATA_H",
        "",
        f"#define SNN_NUM_LAYERS {len(layers)}",
    ]
    for i, layer in enumerate(layers):
        name = getattr(layer, "name", f"layer{i}")
        lines.append(f"#define SNN_LAYER_{i}_SIZE {_layer_size(layer)}  /* {name} */")

    for i, layer in enumerate(layers[1:], start=1):
        weights = _layer_weights(layer)
        if not weights:
            continue
        rows = len(weights)
        cols = len(weights[0]) if weights else 0
        rendered_rows = ", ".join(
            "{" + ", ".join(str(w) for w in row) + "}" for row in weights
        )
        lines.append(
            f"static const float SNN_WEIGHTS_{i}[{rows}][{cols}] = {{{rendered_rows}}};"
        )

    lines.append("")
    lines.append("#endif /* SNN_DATA_H */")
    return "\n".join(lines)


def emit_main_c(layers: list[object], *, n_steps: int, index_bits: int) -> str:
    """Emit the timestep loop driving a non-leaky integrate-and-fire chain.

    Each layer with a weight matrix (``layers[1:]``, per emit_snn_data_h) is
    driven by the previous layer's spikes: accumulate weighted input into a
    membrane potential, fire (and reset by subtracting threshold) once it
    crosses SNN_THRESHOLDS[i]. Layer 0's spikes come straight from the
    (constant, held-across-steps) stimulus in input.h — snn-mlir's supported
    topology has no recurrence, so a static stimulus for the whole run is a
    reasonable stand-in until a real spike-train input format is wired up.

    Layers without a weight matrix are skipped (pass-through) — shouldn't
    happen for a feedforward, fully-connected snn-mlir graph, but the loop
    stays defined for degenerate single-layer graphs.
    """
    index_t = "int64_t" if index_bits == 64 else "int32_t"
    thresholds = ", ".join(str(_layer_threshold(layer)) for layer in layers)

    weighted_layers = [
        (i, layer) for i, layer in enumerate(layers[1:], start=1) if _layer_weights(layer)
    ]
    last_layer = weighted_layers[-1][0] if weighted_layers else 0

    lines = [
        "/* Auto-generated by workers/snn_mlir_compiler/codegen.py — do not edit. */",
        "#include <stdint.h>",
        "#include <stdio.h>",
        "#include <string.h>",
        '#include "snn_data.h"',
        '#include "input.h"',
        "",
        f"typedef {index_t} snn_index_t;",
        f"static const float SNN_THRESHOLDS[SNN_NUM_LAYERS] = {{{thresholds}}};",
        "",
        "static uint8_t spikes_0[SNN_LAYER_0_SIZE];",
    ]
    for i, _layer in weighted_layers:
        lines.append(f"static float mem_{i}[SNN_LAYER_{i}_SIZE] = {{0}};")
        lines.append(f"static uint8_t spikes_{i}[SNN_LAYER_{i}_SIZE];")

    lines += [
        "",
        "int main(void) {",
        "    long total_output_spikes = 0;",
        "",
        f"    for (snn_index_t t = 0; t < {n_steps}; ++t) {{",
        "        for (snn_index_t i = 0; i < SNN_LAYER_0_SIZE; ++i) {",
        "            spikes_0[i] = SNN_INPUT[i] > 0.0f ? 1 : 0;",
        "        }",
    ]

    prev = 0
    for i, _layer in weighted_layers:
        lines += [
            f"        for (snn_index_t j = 0; j < SNN_LAYER_{i}_SIZE; ++j) {{",
            "            float input_sum = 0.0f;",
            f"            for (snn_index_t k = 0; k < SNN_LAYER_{prev}_SIZE; ++k) {{",
            f"                input_sum += SNN_WEIGHTS_{i}[j][k] * (float)spikes_{prev}[k];",
            "            }",
            f"            mem_{i}[j] += input_sum;",
            f"            if (mem_{i}[j] >= SNN_THRESHOLDS[{i}]) {{",
            f"                spikes_{i}[j] = 1;",
            f"                mem_{i}[j] -= SNN_THRESHOLDS[{i}];",
            "            } else {",
            f"                spikes_{i}[j] = 0;",
            "            }",
            "        }",
        ]
        prev = i

    lines += [
        f"        for (snn_index_t o = 0; o < SNN_LAYER_{last_layer}_SIZE; ++o) {{",
        f"            total_output_spikes += spikes_{last_layer}[o];",
        "        }",
        "    }",
        "",
        '    printf("SNN_OUTPUT_SPIKES=%ld\\n", total_output_spikes);',
        "    return 0;",
        "}",
        "",
    ]
    return "\n".join(lines)


def emit_c_artifacts(layers: list[object], *, n_steps: int = 100, index_bits: int = 64) -> CArtifacts:
    return CArtifacts(
        main_c=emit_main_c(layers, n_steps=n_steps, index_bits=index_bits),
        snn_data_h=emit_snn_data_h(layers),
    )
