version: "3.8"

services:
  backend:
    build: .
    ports:
      - "8002:8000"
    volumes:
      - ./neurochip:/app/neurochip
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
