from __future__ import annotations

from typing import TypedDict

import pytest
from hypothesis import given, settings
from hypothesis import strategies as st
from pydantic import ValidationError

from neurosense.contracts.device_contracts import ConnectionTransition, DeviceState
from neurosense.contracts.signal_contracts import FilterOutput

# ---------------------------------------------------------------------------
# FilterOutput property tests
# ---------------------------------------------------------------------------


class FilterOutputPayload(TypedDict):
    data: list[list[float]]
    channels: int
    samples: int
    artifact_rejection_enabled: bool


@st.composite
def filter_output_strategy(draw: st.DrawFn) -> FilterOutputPayload:
    channels = draw(st.integers(min_value=1, max_value=8))
    samples = draw(st.integers(min_value=1, max_value=50))
    artifact_rejection_enabled = draw(st.booleans())

    # Threshold for artifact rejection is 500.0
    max_val = 500.0 if artifact_rejection_enabled else 10000.0

    data = []
    for _ in range(channels):
        channel_data = draw(
            st.lists(
                st.floats(
                    min_value=-max_val, max_value=max_val, allow_nan=False, allow_infinity=False
                ),
                min_size=samples,
                max_size=samples,
            )
        )
        data.append(channel_data)

    return {
        "data": data,
        "channels": channels,
        "samples": samples,
        "artifact_rejection_enabled": artifact_rejection_enabled,
    }


@settings(max_examples=100)
@given(output_data=filter_output_strategy())
def test_filter_output_valid(output_data: FilterOutputPayload) -> None:
    """Verify that FilterOutput accepts valid data generated by the strategy."""
    FilterOutput(**output_data)


@given(
    channels=st.integers(min_value=1, max_value=8), samples=st.integers(min_value=1, max_value=100)
)
def test_filter_output_invalid_shape(channels: int, samples: int) -> None:
    """Verify FilterOutput rejects mismatched channel or sample counts."""
    # Mismatched channel count
    data = [[0.0] * samples for _ in range(channels + 1)]
    with pytest.raises(ValidationError, match="Data channel count"):
        FilterOutput(
            data=data,
            channels=channels,
            samples=samples,
            artifact_rejection_enabled=False,
        )

    # Mismatched sample count in one channel
    if samples > 1:
        data = [[0.0] * samples for _ in range(channels)]
        data[0] = [0.0] * (samples - 1)
        with pytest.raises(ValidationError, match="sample count"):
            FilterOutput(
                data=data,
                channels=channels,
                samples=samples,
                artifact_rejection_enabled=False,
            )


@given(
    channels=st.integers(min_value=1, max_value=4), samples=st.integers(min_value=1, max_value=10)
)
def test_filter_output_non_finite(channels: int, samples: int) -> None:
    """Verify FilterOutput rejects NaN and Inf."""
    data = [[0.0] * samples for _ in range(channels)]
    data[0][0] = float("nan")
    with pytest.raises(ValidationError, match="non-finite values"):
        FilterOutput(
            data=data,
            channels=channels,
            samples=samples,
            artifact_rejection_enabled=False,
        )

    data[0][0] = float("inf")
    with pytest.raises(ValidationError, match="non-finite values"):
        FilterOutput(
            data=data,
            channels=channels,
            samples=samples,
            artifact_rejection_enabled=False,
        )


@given(
    channels=st.integers(min_value=1, max_value=4), samples=st.integers(min_value=1, max_value=10)
)
def test_filter_output_artifact_threshold(channels: int, samples: int) -> None:
    """Verify FilterOutput rejects data exceeding threshold when artifact rejection is on."""
    data = [[0.0] * samples for _ in range(channels)]
    data[0][0] = 501.0
    with pytest.raises(ValidationError, match="exceeds artifact rejection threshold"):
        FilterOutput(data=data, channels=channels, samples=samples, artifact_rejection_enabled=True)

    # Should be fine if artifact rejection is off
    FilterOutput(data=data, channels=channels, samples=samples, artifact_rejection_enabled=False)


# ---------------------------------------------------------------------------
# ConnectionTransition property tests
# ---------------------------------------------------------------------------


@given(from_state=st.sampled_from(DeviceState), to_state=st.sampled_from(DeviceState))
def test_connection_transition_invariants(from_state: DeviceState, to_state: DeviceState) -> None:
    """Verify all state transitions according to the contract."""
    valid_transitions = {
        DeviceState.DISCONNECTED: {DeviceState.CONNECTING},
        DeviceState.CONNECTING: {
            DeviceState.CONNECTED,
            DeviceState.ERROR,
            DeviceState.DISCONNECTED,
        },
        DeviceState.CONNECTED: {DeviceState.DISCONNECTING, DeviceState.ERROR},
        DeviceState.DISCONNECTING: {DeviceState.DISCONNECTED, DeviceState.ERROR},
        DeviceState.ERROR: {DeviceState.DISCONNECTED, DeviceState.CONNECTING},
    }

    is_valid = to_state in valid_transitions[from_state] or from_state == to_state

    if is_valid:
        ConnectionTransition(from_state=from_state, to_state=to_state)
    else:
        with pytest.raises(ValidationError, match="Invalid state transition"):
            ConnectionTransition(from_state=from_state, to_state=to_state)
