"""NeuroCNL Contracts — Pydantic v2 schemas for neuromorphic specifications."""

from .akida_deployment_contract import (
    AKIDA_LIMITS,
    AKIDA_REJECTION_MESSAGES,
    AKIDA_SDK_STATUS_MESSAGES,
    AKIDA_TOPOLOGY,
    AkidaExportResult,
    AkidaHardwareLimits,
    AkidaRejectionReason,
    AkidaSdkIssue,
    AkidaSdkStatus,
    AkidaSupportState,
    AkidaTopologyConstraints,
    AkidaVersion,
    format_akida_rejection,
    normalize_akida_version,
)
from .akida_mapping_contract import (
    AkidaMappedConnection,
    AkidaMappedNetwork,
    AkidaMappedPopulation,
    AkidaMappedProvenance,
)
from .hardware_export import SpiNNakerExportContract
from .neuron_params import (
    LIFNeuronContract,
    PopulationContract,
    STDPContract,
    SynapticContract,
)
from .pipeline_contracts import (
    AssertionResultContract,
    CNLParseResultContract,
    ErrorDetailContract,
    Layer1ResultContract,
    Layer2ResultContract,
    ParsedSentenceContract,
    PipelineResultContract,
    SimulationResultContract,
    ValidationResultContract,
)
from .pynq_deployment_contract import (
    PYNQ_LIMITS,
    PynqExportResult,
    PynqHardwareLimits,
    PynqRejectionReason,
    PynqSupportState,
)
from .pynq_runtime_artifact_contract import (
    PynqOverlayConfigContract,
    PynqRegisterMap,
    PynqRuntimeArtifact,
    validate_pynq_artifact_completeness,
)
from .teensy_deployment_contract import (
    REJECTION_MESSAGES,
    TEENSY_LIMITS,
    TEENSY_TOPOLOGY,
    TeensyDeployabilityVerdict,
    TeensyDeploymentResult,
    TeensyHardwareLimits,
    TeensyIOMapping,
    TeensyRejectionReason,
    TeensyTopologyConstraints,
)

__all__ = [
    "LIFNeuronContract",
    "SynapticContract",
    "STDPContract",
    "PopulationContract",
    "AKIDA_LIMITS",
    "AKIDA_REJECTION_MESSAGES",
    "format_akida_rejection",
    "AKIDA_SDK_STATUS_MESSAGES",
    "AKIDA_TOPOLOGY",
    "AkidaVersion",
    "normalize_akida_version",
    "AkidaHardwareLimits",
    "AkidaTopologyConstraints",
    "AkidaSdkStatus",
    "AkidaSdkIssue",
    "AkidaSupportState",
    "AkidaRejectionReason",
    "AkidaExportResult",
    "AkidaMappedProvenance",
    "AkidaMappedPopulation",
    "AkidaMappedConnection",
    "AkidaMappedNetwork",
    "SpiNNakerExportContract",
    "ErrorDetailContract",
    "ParsedSentenceContract",
    "CNLParseResultContract",
    "Layer1ResultContract",
    "Layer2ResultContract",
    "ValidationResultContract",
    "SimulationResultContract",
    "AssertionResultContract",
    "PipelineResultContract",
    "TeensyHardwareLimits",
    "TeensyTopologyConstraints",
    "TeensyIOMapping",
    "TeensyDeployabilityVerdict",
    "TeensyRejectionReason",
    "TeensyDeploymentResult",
    "TEENSY_LIMITS",
    "TEENSY_TOPOLOGY",
    "REJECTION_MESSAGES",
    "PYNQ_LIMITS",
    "PynqHardwareLimits",
    "PynqSupportState",
    "PynqRejectionReason",
    "PynqExportResult",
    "PynqOverlayConfigContract",
    "PynqRegisterMap",
    "PynqRuntimeArtifact",
    "validate_pynq_artifact_completeness",
]
