"""Property tests for WorkflowDefinition and WorkflowTemplate contracts."""

from typing import Any

import pytest
from hypothesis import given, settings
from hypothesis import strategies as st
from pydantic import ValidationError

from neurohub.contracts.workflow_contracts import (
    ContractWorkflowStep,
    WorkflowDefinition,
    WorkflowStep,
    WorkflowTemplate,
)


@st.composite
def workflow_definition_strategy(draw: st.DrawFn) -> WorkflowDefinition:
    """Hypothesis strategy for generating a valid WorkflowDefinition."""
    # Generate a small number of steps to keep it manageable and likely to be DAG
    num_steps = draw(st.integers(min_value=1, max_value=10))
    step_ids = [f"step_{i}" for i in range(num_steps)]

    steps = []
    for i, step_id in enumerate(step_ids):
        # To ensure it is a DAG, only depend on previous steps
        if i > 0:
            dependencies = draw(st.lists(st.sampled_from(step_ids[:i]), unique=True))
        else:
            dependencies = []
        steps.append(ContractWorkflowStep(id=step_id, depends_on=dependencies))

    # Execution order must contain all or subset of step IDs
    execution_order = draw(st.lists(st.sampled_from(step_ids), unique=True, min_size=1))

    return WorkflowDefinition(steps=steps, execution_order=execution_order)


@st.composite
def workflow_template_strategy(draw: st.DrawFn) -> WorkflowTemplate:
    """Hypothesis strategy for generating a valid WorkflowTemplate."""
    num_steps = draw(st.integers(min_value=1, max_value=10))
    step_ids = [f"step_{i}" for i in range(num_steps)]

    steps = []
    # To avoid isolated steps in a multi-step workflow:
    # Each step i > 0 must either depend on some step < i,
    # OR some step > i must depend on step i.
    # A simple way to ensure no isolated steps is to make it a chain:
    # step i depends on step i-1 (for i > 0).
    for i, step_id in enumerate(step_ids):
        # Build a chain to avoid isolated steps: step_i depends on step_i-1
        if i > 0:
            # At least depend on the previous step to avoid isolation
            dependencies = draw(st.lists(st.sampled_from(step_ids[:i]), min_size=1, unique=True))
        else:
            dependencies = []

        steps.append(
            WorkflowStep(
                id=step_id,
                name=draw(st.text(min_size=1, max_size=20)),
                app=draw(st.sampled_from(["neurosim", "neurochip", "neurobench", "neurosense"])),
                endpoint=draw(st.text(min_size=1, max_size=30)),
                method=draw(st.sampled_from(["GET", "POST"])),
                parameters=draw(st.dictionaries(st.text(min_size=1), st.text())),
                success_criteria=draw(st.text(min_size=1, max_size=30)),
                on_failure=draw(st.sampled_from(["halt", "warn", "skip"])),
                depends_on=dependencies,
                timeout_seconds=draw(st.integers(min_value=1, max_value=600)),
            )
        )

    return WorkflowTemplate(
        id=draw(st.uuids().map(str)),
        name=draw(st.text(min_size=1, max_size=50)),
        description=draw(st.text()),
        steps=steps,
        builtin=draw(st.booleans()),
    )


@settings(max_examples=200)
@given(workflow_definition_strategy())
def test_generated_workflows_are_valid_dags(workflow: WorkflowDefinition) -> None:
    """Test that all workflows generated by the DAG strategy are valid."""
    assert isinstance(workflow, WorkflowDefinition)


@settings(max_examples=200)
@given(workflow_definition_strategy())
def test_workflow_definition_round_trip(workflow: WorkflowDefinition) -> None:
    """Test serialization round-trip for WorkflowDefinition."""
    dumped = workflow.model_dump_json()
    reloaded = WorkflowDefinition.model_validate_json(dumped)
    assert reloaded == workflow


@settings(max_examples=200)
@given(workflow_template_strategy())
def test_workflow_template_round_trip(template: WorkflowTemplate) -> None:
    """Test serialization round-trip for WorkflowTemplate."""
    dumped = template.model_dump_json()
    reloaded = WorkflowTemplate.model_validate_json(dumped)
    assert reloaded == template


@settings(max_examples=200)
@given(
    st.lists(
        st.fixed_dictionaries(
            {
                "id": st.text(min_size=1, max_size=10),
                "depends_on": st.lists(st.text(min_size=1, max_size=10), unique=True),
            }
        ),
        min_size=1,
        max_size=10,
        unique_by=lambda x: str(x["id"]),
    )
)
def test_workflow_cycle_detection(steps_data: list[dict[str, Any]]) -> None:
    """Test that any cyclic workflow is rejected."""
    steps = [ContractWorkflowStep(**s) for s in steps_data]
    step_ids = {s.id for s in steps}

    # Ensure all dependencies exist to focus only on cycle detection
    for s in steps:
        s.depends_on = [d for d in s.depends_on if d in step_ids]

    # Try to create a cycle if not already present to stress test
    if len(steps) >= 2:
        steps[0].depends_on = [steps[1].id]
        if steps[0].id not in steps[1].depends_on:
            steps[1].depends_on.append(steps[0].id)

    try:
        WorkflowDefinition(steps=steps, execution_order=[s.id for s in steps])
    except (ValidationError, ValueError) as e:
        errors = str(e)
        if "Workflow graph contains cycles" in errors:
            return  # Success: cycle detected

    adj = {step.id: step.depends_on for step in steps}
    visited = set()
    path = set()

    def has_cycle(v: str) -> bool:
        visited.add(v)
        path.add(v)
        for neighbor in adj.get(v, []):
            if neighbor not in visited:
                if has_cycle(neighbor):
                    return True
            elif neighbor in path:
                return True
        path.remove(v)
        return False

    for step_id in adj:
        if step_id not in visited:
            if has_cycle(step_id):
                pytest.fail(f"Cycle detected in steps {steps_data} but contract allowed it")


@settings(max_examples=200)
@given(workflow_definition_strategy())
def test_workflow_definition_rejects_invalid_execution_order(workflow: WorkflowDefinition) -> None:
    """Test that WorkflowDefinition rejects execution_order referring to non-existent steps."""
    invalid_id = "non_existent_step"
    # Ensure invalid_id is not already in steps
    step_ids = {s.id for s in workflow.steps}
    while invalid_id in step_ids:
        invalid_id += "_"

    workflow_dict = workflow.model_dump()
    workflow_dict["execution_order"].append(invalid_id)

    with pytest.raises(ValidationError) as excinfo:
        WorkflowDefinition(**workflow_dict)

    assert "Execution order step reference not found" in str(excinfo.value)


@settings(max_examples=200)
@given(
    st.lists(
        st.fixed_dictionaries(
            {
                "id": st.text(min_size=1, max_size=10),
                "name": st.text(min_size=1, max_size=20),
                "app": st.sampled_from(["neurosim", "neurochip"]),
                "endpoint": st.text(min_size=1, max_size=20),
                "method": st.sampled_from(["GET", "POST"]),
                "parameters": st.dictionaries(st.text(), st.text()),
                "success_criteria": st.text(min_size=1, max_size=20),
                "on_failure": st.sampled_from(["halt", "warn", "skip"]),
                "depends_on": st.lists(st.text(min_size=1, max_size=10), unique=True),
            }
        ),
        min_size=1,
        max_size=5,
        unique_by=lambda x: str(x["id"]),
    )
)
def test_workflow_template_dag_integrity(steps_data: list[dict[str, Any]]) -> None:
    """Test that WorkflowTemplate correctly validates its DAG."""
    steps = [WorkflowStep(**s) for s in steps_data]
    step_ids = {s.id for s in steps}

    try:
        WorkflowTemplate(
            id="test_wf", name="Test Workflow", description="desc", steps=steps, builtin=True
        )
    except (ValidationError, ValueError) as e:
        errors = str(e)
        # Check if failure is due to missing reference or cycle
        if "Dependency step reference not found" in errors or "contains cycles" in errors:
            return  # Valid rejection

    # If it passed validation, it MUST be a valid DAG
    for s in steps:
        for dep in s.depends_on:
            assert dep in step_ids

    adj = {step.id: step.depends_on for step in steps}
    visited = set()
    path = set()

    def has_cycle(v: str) -> bool:
        visited.add(v)
        path.add(v)
        for neighbor in adj.get(v, []):
            if neighbor not in visited:
                if has_cycle(neighbor):
                    return True
            elif neighbor in path:
                return True
        path.remove(v)
        return False

    for step_id in adj:
        if step_id not in visited:
            if has_cycle(step_id):
                pytest.fail("Cycle detected in WorkflowTemplate but contract allowed it")
