"""Build a standalone Nengo script from a serialized graph."""

from __future__ import annotations

import re
from typing import Any


def export_nengo_code(
    graph: dict[str, list[dict[str, Any]]],
    label: str = "generated_network",
    *,
    dt: float = 1e-4,
    presentation_time: float = 1e-4,
    probes: list[str] | tuple[str, ...] = ("spikes",),
) -> str:
    """Render a deterministic Python script from a serialized network graph."""
    lines = [
        '"""Standalone Nengo script auto-generated by neurocnl.',
        "",
        "Safe to open in Nengo GUI.",
        "Run as a standalone script with: python exported_network.py",
        '"""',
        "",
        "import nengo",
        "import numpy as np",
        "",
        f"model = nengo.Network(label={label!r})",
        "with model:",
    ]

    declared_vars: dict[str, str] = {}
    used_vars: set[str] = set()
    connection_vars: dict[str, str] = {}

    for node in graph.get("nodes", []):
        node_id = str(node["id"])
        var_name = _python_identifier(node_id, used_vars)
        declared_vars[node_id] = var_name
        node_type = node.get("type")
        params = node.get("params", {})

        if node_type == "input_node":
            lines.append(f"    {var_name} = nengo.Node(0.0, label={node_id!r})")
            continue

        if node_type == "ensemble":
            n_neurons = int(params.get("n_neurons", 50))
            dimensions = int(params.get("dimensions", 1))
            tau_rc = float(params.get("tau_rc", 0.02))
            tau_ref = float(params.get("tau_ref", 0.002))
            radius = float(params.get("radius", 1.0))
            neuron_type = params.get("neuron_type", "LIF")
            tau_n = params.get("tau_n")
            neuron_ctor = _neuron_type_ctor(
                neuron_type,
                tau_rc=tau_rc,
                tau_ref=tau_ref,
                tau_n=float(tau_n) if tau_n is not None else None,
            )
            ensemble_lines = [
                f"    {var_name} = nengo.Ensemble(",
                f"        n_neurons={n_neurons},",
                f"        dimensions={dimensions},",
                f"        radius={radius!r},",
                f"        neuron_type={neuron_ctor},",
            ]
            intercepts_line = _distribution_line(
                "intercepts", params, "intercepts_low", "intercepts_high"
            )
            if intercepts_line is not None:
                ensemble_lines.append(intercepts_line)
            max_rates_line = _distribution_line(
                "max_rates", params, "max_rates_low", "max_rates_high"
            )
            if max_rates_line is not None:
                ensemble_lines.append(max_rates_line)
            ensemble_lines.extend(
                [
                    f"        label={node_id!r},",
                    "    )",
                ]
            )
            lines.extend(ensemble_lines)
            continue

        lines.append(f"    # Unsupported node type {node_type!r} for {node_id!r}")

    if graph.get("edges"):
        lines.append("")

    deferred_edges: list[dict[str, Any]] = []
    for edge in graph.get("edges", []):
        source_id = str(edge["source"])
        target_id = str(edge["target"])
        source_var = declared_vars.get(source_id)
        target_var = declared_vars.get(target_id)

        if source_var is None or target_var is None:
            deferred_edges.append(edge)
            continue

        edge_var = _python_identifier(str(edge["id"]), used_vars)
        params = edge.get("params", {})
        conn_args = [
            _endpoint_expr(source_var, params.get("source_selector")),
            _endpoint_expr(target_var, params.get("target_selector")),
        ]
        transform = params.get("transform")
        synapse = params.get("synapse")

        if transform is not None:
            conn_args.append(f"transform={_transform_expr(transform)}")
        if synapse is not None:
            conn_args.append(f"synapse=nengo.Lowpass({float(synapse)!r})")

        learning_rule = _learning_rule_ctor(edge)
        if learning_rule is not None:
            conn_args.append(f"learning_rule_type={learning_rule}")

        lines.append(f"    {edge_var} = nengo.Connection({', '.join(conn_args)})")
        connection_vars[str(edge["id"])] = edge_var

    if deferred_edges:
        lines.append("")
        emitted_header = False
        for edge in deferred_edges:
            source_id = str(edge["source"])
            target_id = str(edge["target"])
            source_var = declared_vars.get(source_id)
            base_connection_id = (
                target_id[: -len("_learning_rule")]
                if target_id.endswith("_learning_rule")
                else None
            )
            connection_var = (
                connection_vars.get(base_connection_id) if base_connection_id is not None else None
            )
            if source_var is not None and connection_var is not None:
                edge_var = _python_identifier(str(edge["id"]), used_vars)
                lines.append(
                    f"    {edge_var} = nengo.Connection({source_var}, {connection_var}.learning_rule)"
                )
                continue

            if not emitted_header:
                lines.append("    # Edges below could not be reconstructed as standalone nodes.")
                emitted_header = True
            lines.append(
                "    # Skipped edge: "
                f"{edge.get('source')!r} -> {edge.get('target')!r} "
                f"({edge.get('learning_rule') or 'static'})"
            )

    probe_targets = [node for node in graph.get("nodes", []) if node.get("type") == "ensemble"]
    if probe_targets:
        lines.append("")
        probe_vars: dict[str, str] = {}
        for node in probe_targets:
            node_id = str(node["id"])
            var_name = declared_vars[node_id]
            probe_var = _python_identifier(f"{node_id}_probe", used_vars)
            probe_vars[node_id] = probe_var
            if "spikes" in probes:
                lines.append(f"    {probe_var} = nengo.Probe({var_name}.neurons, synapse=0.01)")
            if "voltage" in probes:
                vol_var = _python_identifier(f"{node_id}_voltage_probe", used_vars)
                lines.append(f"    {vol_var} = nengo.Probe({var_name}.neurons, 'voltage')")
            if "decoded" in probes:
                dec_var = _python_identifier(f"{node_id}_decoded_probe", used_vars)
                lines.append(f"    {dec_var} = nengo.Probe({var_name}, synapse=0.01)")

        lines.extend(
            [
                "",
                "",
                "if __name__ == '__main__':",
                f"    with nengo.Simulator(model, dt={dt!r}) as sim:",
                f"        sim.run({presentation_time!r})  # presentation_time in seconds",
                "",
            ]
        )
        for node in probe_targets:
            node_id = str(node["id"])
            probe_var = probe_vars[node_id]
            lines.append(f"    print({node_id!r}, np.asarray(sim.data[{probe_var}])[-1].tolist())")
    else:
        lines.extend(
            [
                "",
                "if __name__ == '__main__':",
                f"    with nengo.Simulator(model, dt={dt!r}) as sim:",
                f"        sim.run({presentation_time!r})  # presentation_time in seconds",
            ]
        )

    return "\n".join(lines) + "\n"


def _learning_rule_ctor(edge: dict[str, Any]) -> str | None:
    rule_name = edge.get("learning_rule")
    if not edge.get("has_learning_rule") or not isinstance(rule_name, str):
        return None

    learning_rate = edge.get("learning_rate")
    suffix = f"(learning_rate={float(learning_rate)!r})" if learning_rate is not None else "()"
    if rule_name in {"PES", "BCM", "Oja"}:
        return f"nengo.{rule_name}{suffix}"
    return None


def _neuron_type_ctor(
    neuron_type: Any,
    *,
    tau_rc: float,
    tau_ref: float,
    tau_n: float | None = None,
) -> str:
    if neuron_type == "AdaptiveLIF":
        extras = f", tau_n={tau_n!r}" if tau_n is not None else ""
        return f"nengo.AdaptiveLIF(tau_rc={tau_rc!r}, tau_ref={tau_ref!r}{extras})"
    return f"nengo.LIF(tau_rc={tau_rc!r}, tau_ref={tau_ref!r})"


def _distribution_line(
    arg_name: str,
    params: dict[str, Any],
    low_key: str,
    high_key: str,
) -> str | None:
    low = params.get(low_key)
    high = params.get(high_key)
    if low is None or high is None:
        return None
    return f"        {arg_name}=nengo.dists.Uniform({float(low)!r}, {float(high)!r}),"


def _endpoint_expr(var_name: str, selector: Any) -> str:
    if selector == "neurons":
        return f"{var_name}.neurons"
    return var_name


def _transform_expr(transform: Any) -> str:
    if isinstance(transform, list):
        return f"np.asarray({transform!r}, dtype=float)"
    return repr(float(transform))


def _python_identifier(label: str, used: set[str], *, reserve: bool = True) -> str:
    identifier = re.sub(r"\W+", "_", label.strip().lower()).strip("_") or "node"
    if identifier[0].isdigit():
        identifier = f"node_{identifier}"

    candidate = identifier
    counter = 2
    while candidate in used:
        candidate = f"{identifier}_{counter}"
        counter += 1

    if reserve:
        used.add(candidate)
    return candidate
