#ifndef NEUROCNL_NETWORK_H
#define NEUROCNL_NETWORK_H

/* Auto-generated by neurocnl export */

#include <stdint.h>

#define NUM_POPULATIONS 2

/* Population: sensory neuron */
#define SENSORY_NEURON_N_NEURONS 50
#define SENSORY_NEURON_INDEX 0
static const float SENSORY_NEURON_TAU_RC = 0.05f;
static const float SENSORY_NEURON_TAU_REF = 0.003f;

/* Population: motor neuron */
#define MOTOR_NEURON_N_NEURONS 50
#define MOTOR_NEURON_INDEX 50
static const float MOTOR_NEURON_TAU_RC = 0.05f;
static const float MOTOR_NEURON_TAU_REF = 0.003f;

#define TOTAL_NEURONS 100

/* Connection weights */
static const float W_SENSORY_NEURON_TO_MOTOR_NEURON = 0.8f;

/* LIF neuron state */
static float voltage[TOTAL_NEURONS];
static float refractory[TOTAL_NEURONS];
static uint8_t spikes[TOTAL_NEURONS];

/**
 * Update all LIF neurons for one timestep.
 * @param dt Timestep in seconds
 * @param input Array of input currents (one per neuron)
 */
static inline void lif_step(const float dt, const float* input) {
    for (int i = 0; i < TOTAL_NEURONS; i++) {
        spikes[i] = 0;
        if (refractory[i] > 0.0f) {
            refractory[i] -= dt;
            continue;
        }
        /* dv/dt = (0 - v) / tau_rc + input / tau_rc */
        voltage[i] += dt * (-voltage[i] + input[i]);
        if (voltage[i] >= 1.0f) {
            spikes[i] = 1;
            voltage[i] = 0.0f;
            refractory[i] = 0.002f; /* default tau_ref */
        }
    }
}

#endif /* NEUROCNL_NETWORK_H */
