"""C header exporter for embedded microcontrollers.

Generates a C header file with LIF neuron parameters, weight arrays,
and a basic LIF update loop suitable for Teensy 4.1 or similar ARM
microcontrollers.
"""

import nengo


def export_c_header(
    net: nengo.Network,
    *,
    guard_name: str = "NEUROCNL_NETWORK_H",
    precision: str = "float",
) -> str:
    """Export a Nengo network to a C header file.

    Parameters
    ----------
    net : nengo.Network
        A Nengo network with populations and connections.
    guard_name : str
        Include guard name for the header.
    precision : str
        C type for numeric values: 'float' or 'double'.

    Returns
    -------
    str
        C header file contents.
    """
    lines = [
        f"#ifndef {guard_name}",
        f"#define {guard_name}",
        "",
        "/* Auto-generated by neurocnl export */",
        "",
        "#include <stdint.h>",
        "",
    ]

    # Collect ensemble parameters
    ensembles = list(net.all_ensembles)
    lines.append(f"#define NUM_POPULATIONS {len(ensembles)}")
    lines.append("")

    total_neurons = 0
    for i, ens in enumerate(ensembles):
        label = (ens.label or f"pop_{i}").replace(" ", "_").replace("-", "_").upper()
        lines.append(f"/* Population: {ens.label or f'pop_{i}'} */")
        lines.append(f"#define {label}_N_NEURONS {ens.n_neurons}")
        lines.append(f"#define {label}_INDEX {total_neurons}")

        nt = ens.neuron_type
        if isinstance(nt, nengo.LIF):
            lines.append(f"static const {precision} {label}_TAU_RC = {nt.tau_rc}f;")
            lines.append(f"static const {precision} {label}_TAU_REF = {nt.tau_ref}f;")
        lines.append("")
        total_neurons += ens.n_neurons

    lines.append(f"#define TOTAL_NEURONS {total_neurons}")
    lines.append("")

    # Export connection weights as arrays
    lines.append("/* Connection weights */")
    for i, conn in enumerate(net.all_connections):
        pre = conn.pre_obj
        post = conn.post_obj
        pre_ens = pre if isinstance(pre, nengo.Ensemble) else getattr(pre, "ensemble", None)
        post_ens = post if isinstance(post, nengo.Ensemble) else getattr(post, "ensemble", None)

        if pre_ens and post_ens:
            pre_label = (pre_ens.label or "pop").replace(" ", "_").replace("-", "_")
            post_label = (post_ens.label or "pop").replace(" ", "_").replace("-", "_")
            conn_label = f"W_{pre_label}_to_{post_label}".upper()

            weight = 1.0
            if hasattr(conn, "transform"):
                t = conn.transform
                if hasattr(t, "init"):
                    w = t.init
                    if isinstance(w, int | float):
                        weight = float(w)
                    elif hasattr(w, "flat"):
                        weight = float(w.flat[0]) if w.size > 0 else 1.0

            lines.append(f"static const {precision} {conn_label} = {weight}f;")

    lines.append("")

    # LIF update loop
    lines.extend(
        [
            "/* LIF neuron state */",
            f"static {precision} voltage[TOTAL_NEURONS];",
            f"static {precision} refractory[TOTAL_NEURONS];",
            "static uint8_t spikes[TOTAL_NEURONS];",
            "",
            "/**",
            " * Update all LIF neurons for one timestep.",
            " * @param dt Timestep in seconds",
            " * @param input Array of input currents (one per neuron)",
            " */",
            f"static inline void lif_step(const {precision} dt, const {precision}* input) {{",
            "    for (int i = 0; i < TOTAL_NEURONS; i++) {",
            "        spikes[i] = 0;",
            "        if (refractory[i] > 0.0f) {",
            "            refractory[i] -= dt;",
            "            continue;",
            "        }",
            "        /* dv/dt = (0 - v) / tau_rc + input / tau_rc */",
            "        voltage[i] += dt * (-voltage[i] + input[i]);",
            "        if (voltage[i] >= 1.0f) {",
            "            spikes[i] = 1;",
            "            voltage[i] = 0.0f;",
            "            refractory[i] = 0.002f; /* default tau_ref */",
            "        }",
            "    }",
            "}",
            "",
            f"#endif /* {guard_name} */",
            "",
        ]
    )

    return "\n".join(lines)
