"""Intel Lava framework exporter.

Generates Python code using the Lava Process/ProcessModel pattern
for deployment on Intel neuromorphic hardware.
"""

import logging
from typing import Any

import nengo


def export_lava(net: nengo.Network, hw_mode: bool = False, **kwargs: Any) -> str:
    """Export a Nengo network as Lava Process definitions.

    Parameters
    ----------
    net : nengo.Network
        A Nengo network.

    Returns
    -------
    str
        Python code string for Lava deployment.
    """
    lines = [
        '"""Lava Process definitions — auto-generated by neurocnl."""',
        "",
        "import numpy as np",
        "from lava.proc.lif.process import LIF",
        "from lava.proc.dense.process import Dense",
        "from lava.magma.core.run_configs import Loihi2SimCfg, Loihi2HwCfg",
        "from lava.magma.core.run_conditions import RunSteps",
        "",
    ]

    # Create LIF populations
    ensemble_vars: dict[int, str] = {}
    for i, ens in enumerate(net.all_ensembles):
        var_name = (ens.label or f"pop_{i}").replace(" ", "_").replace("-", "_")
        ensemble_vars[id(ens)] = var_name
        nt = ens.neuron_type
        # Lava LIF uses different parameterization
        # Convert membrane time constant (tau_rc) to voltage decay (du). Formula: du = int(1.0 / tau_rc).
        du = int(1.0 / nt.tau_rc) if isinstance(nt, nengo.LIF) and nt.tau_rc > 0 else 50
        vth = 128  # Lava uses integer threshold
        lines.append(f"# Population: {ens.label or var_name}")
        lines.append(
            f"{var_name} = LIF(shape=({ens.n_neurons},), du={du}, dv=1, vth={vth})"
        )
        lines.append("")

    # Create Dense connections
    for i, conn in enumerate(net.all_connections):
        pre = conn.pre_obj
        post = conn.post_obj
        pre_ens = (
            pre if isinstance(pre, nengo.Ensemble) else getattr(pre, "ensemble", None)
        )
        post_ens = (
            post
            if isinstance(post, nengo.Ensemble)
            else getattr(post, "ensemble", None)
        )

        if (
            pre_ens
            and post_ens
            and id(pre_ens) in ensemble_vars
            and id(post_ens) in ensemble_vars
        ):
            pre_var = ensemble_vars[id(pre_ens)]
            post_var = ensemble_vars[id(post_ens)]

            weight = 1.0
            if hasattr(conn, "transform"):
                t = conn.transform
                if hasattr(t, "init"):
                    w = t.init
                    if isinstance(w, int | float):
                        weight = float(w)
                    elif hasattr(w, "flat"):
                        weight = float(w.flat[0]) if w.size > 0 else 1.0

            # Scale Nengo floating-point weights to Lava integer range (scale factor: 128).
            int_weight = int(weight * 128)
            n_pre = pre_ens.n_neurons
            n_post = post_ens.n_neurons
            conn_var = f"conn_{pre_var}_to_{post_var}"
            lines.append(f"# Connection: {pre_var} -> {post_var}")
            lines.append(
                f"{conn_var} = Dense(weights=np.full(({n_post}, {n_pre}), {int_weight}))"
            )
            lines.append(f"{pre_var}.s_out.connect({conn_var}.s_in)")
            lines.append(f"{conn_var}.a_out.connect({post_var}.a_in)")
            lines.append("")

    ir = kwargs.get("ir")
    num_steps = 100
    found_sim_time = False
    if ir and hasattr(ir, "timing_declarations"):
        for decl in ir.timing_declarations:
            if (
                getattr(decl, "kind", "") == "simulation_time"
                and getattr(decl, "value", None) is not None
            ):
                num_steps = int(decl.value * 1000)
                found_sim_time = True
                break

    if not found_sim_time:
        logging.warning("Simulation time not provided; defaulting to 100 RunSteps.")

    # Run configuration
    lines.extend(
        [
            "# --- Run simulation ---",
            f"run_cfg = {'Loihi2HwCfg()' if hw_mode else 'Loihi2SimCfg()'}",
            f"run_cond = RunSteps(num_steps={num_steps})",
            (
                f"{list(ensemble_vars.values())[0]}.run(condition=run_cond, run_cfg=run_cfg)"
                if ensemble_vars
                else "# No populations to run"
            ),
            f"{list(ensemble_vars.values())[0]}.stop()" if ensemble_vars else "",
        ]
    )

    return "\n".join(lines)
