"""NengoLoihi compilation helper.

Generates Python code that wraps a Nengo network for deployment
on Intel Loihi 2 via the NengoLoihi compiler.
"""

import nengo


def export_loihi(
    net: nengo.Network,
    *,
    target: str = "loihi",
) -> str:
    """Export a Nengo network as NengoLoihi-compatible Python code.

    Parameters
    ----------
    net : nengo.Network
        A Nengo network.
    target : str
        Target: 'loihi' (hardware) or 'emulator'.

    Returns
    -------
    str
        Python code string for NengoLoihi deployment.
    """
    lines = [
        '"""NengoLoihi deployment code — auto-generated by neurocnl."""',
        "",
        "import nengo",
        "import nengo_loihi",
        "import numpy as np",
        "",
    ]

    # Generate network reconstruction code
    lines.append("# --- Network Definition ---")
    lines.append(f'net = nengo.Network(label="{net.label or "neurocnl_network"}")')
    lines.append("with net:")

    # Enumerate ensembles
    ensemble_vars = {}
    for i, ens in enumerate(net.all_ensembles):
        var_name = (ens.label or f"pop_{i}").replace(" ", "_").replace("-", "_")
        ensemble_vars[id(ens)] = var_name
        nt = ens.neuron_type
        tau_rc = nt.tau_rc if isinstance(nt, nengo.LIF) else 0.02
        tau_ref = nt.tau_ref if isinstance(nt, nengo.LIF) else 0.002
        lines.append(f"    {var_name} = nengo.Ensemble(")
        lines.append(f"        n_neurons={ens.n_neurons},")
        lines.append(f"        dimensions={ens.dimensions},")
        lines.append(f"        neuron_type=nengo.LIF(tau_rc={tau_rc}, tau_ref={tau_ref}),")
        lines.append(f'        label="{ens.label or var_name}",')
        lines.append("    )")

    # Enumerate connections
    for i, conn in enumerate(net.all_connections):
        pre = conn.pre_obj
        post = conn.post_obj
        pre_ens = pre if isinstance(pre, nengo.Ensemble) else getattr(pre, "ensemble", None)
        post_ens = post if isinstance(post, nengo.Ensemble) else getattr(post, "ensemble", None)

        if pre_ens and post_ens and id(pre_ens) in ensemble_vars and id(post_ens) in ensemble_vars:
            pre_var = ensemble_vars[id(pre_ens)]
            post_var = ensemble_vars[id(post_ens)]

            weight = 1.0
            if hasattr(conn, "transform"):
                t = conn.transform
                if hasattr(t, "init"):
                    w = t.init
                    if isinstance(w, int | float):
                        weight = float(w)
                    elif hasattr(w, "flat"):
                        weight = float(w.flat[0]) if w.size > 0 else 1.0

            lines.append(f"    nengo.Connection({pre_var}, {post_var}, transform={weight})")

    lines.append("")

    # Loihi configuration
    lines.extend(
        [
            "# --- Loihi Configuration ---",
            "# Block shapes for efficient mapping to Loihi neurocores",
            "with net:",
            "    nengo_loihi.add_params(net)",
        ]
    )

    for ens_id, var_name in ensemble_vars.items():
        lines.append(
            f"    net.config[{var_name}].block_shape = "
            f"nengo_loihi.BlockShape((32,), ({var_name}.n_neurons,))"
        )

    lines.append("")

    # Simulator
    if target == "emulator":
        lines.extend(
            [
                "# --- Run on Emulator ---",
                "with nengo_loihi.Simulator(net, target='sim') as sim:",
                "    sim.run(1.0)",
            ]
        )
    else:
        lines.extend(
            [
                "# --- Run on Loihi Hardware ---",
                "with nengo_loihi.Simulator(net) as sim:",
                "    sim.run(1.0)",
            ]
        )

    return "\n".join(lines)
