"""SpiNNaker exporter via PyNN.

Generates Python code using the PyNN API for deployment on the
SpiNNaker neuromorphic platform.
"""

from typing import Any

import nengo


def export_spinnaker(net: nengo.Network, **kwargs: Any) -> str:
    """Export a Nengo network as PyNN/SpiNNaker code.

    Parameters
    ----------
    net : nengo.Network
        A Nengo network.

    Returns
    -------
    str
        Python code string for PyNN/SpiNNaker.
    """
    lines = [
        '"""PyNN/SpiNNaker code — auto-generated by neurocnl."""',
        "",
        "import pyNN.spiNNaker as sim",
        "import numpy as np",
        "",
        "sim.setup(timestep=1.0)  # 1ms timestep",
        "",
    ]

    # Create populations
    ensemble_vars: dict[int, str] = {}
    for i, ens in enumerate(net.all_ensembles):
        var_name = (ens.label or f"pop_{i}").replace(" ", "_").replace("-", "_")
        ensemble_vars[id(ens)] = var_name
        nt = ens.neuron_type
        tau_m = nt.tau_rc * 1000 if isinstance(nt, nengo.LIF) else 20.0  # Convert to ms
        tau_refrac = nt.tau_ref * 1000 if isinstance(nt, nengo.LIF) else 2.0
        lines.append(f"# Population: {ens.label or var_name}")
        lines.append(f"{var_name} = sim.Population(")
        lines.append(f"    {ens.n_neurons},")
        lines.append("    sim.IF_curr_exp(")
        lines.append(f"        tau_m={tau_m:.1f},")
        lines.append(f"        tau_refrac={tau_refrac:.1f},")
        lines.append("        v_thresh=-50.0,")
        lines.append("        v_reset=-65.0,")
        lines.append("        v_rest=-65.0,")
        lines.append("    ),")
        lines.append(f'    label="{ens.label or var_name}",')
        lines.append(")")
        lines.append("")

    # Create projections
    for i, conn in enumerate(net.all_connections):
        pre = conn.pre_obj
        post = conn.post_obj
        pre_ens = (
            pre if isinstance(pre, nengo.Ensemble) else getattr(pre, "ensemble", None)
        )
        post_ens = (
            post
            if isinstance(post, nengo.Ensemble)
            else getattr(post, "ensemble", None)
        )

        if (
            pre_ens
            and post_ens
            and id(pre_ens) in ensemble_vars
            and id(post_ens) in ensemble_vars
        ):
            pre_var = ensemble_vars[id(pre_ens)]
            post_var = ensemble_vars[id(post_ens)]

            weight = 1.0
            if hasattr(conn, "transform"):
                t = conn.transform
                if hasattr(t, "init"):
                    w = t.init
                    if isinstance(w, int | float):
                        weight = float(w)
                    elif hasattr(w, "flat"):
                        weight = float(w.flat[0]) if w.size > 0 else 1.0

            receptor = "inhibitory" if weight < 0 else "excitatory"
            lines.append(f"# Projection: {pre_var} -> {post_var}")
            lines.append("sim.Projection(")
            lines.append(f"    {pre_var}, {post_var},")
            lines.append("    sim.AllToAllConnector(),")
            lines.append(
                f"    synapse_type=sim.StaticSynapse(weight={abs(weight):.4f}),"
            )
            lines.append(f'    receptor_type="{receptor}",')
            lines.append(")")
            lines.append("")

    # Recording and running
    for var_name in ensemble_vars.values():
        lines.append(f'{var_name}.record(["spikes", "v"])')

    lines.extend(
        [
            "",
            "sim.run(1000)  # Run for 1000ms",
            "",
            "# Retrieve data",
        ]
    )

    for var_name in ensemble_vars.values():
        lines.append(f"{var_name}_data = {var_name}.get_data()")

    lines.extend(
        [
            "",
            "sim.end()",
        ]
    )

    return "\n".join(lines)
