"""SpiNNaker2 exporter using py-spinnaker2.

Generates Python code using the py-spinnaker2 API for deployment on the
SpiNNcloud/SpiNNaker2 platform.
"""

from typing import Any

import nengo
import numpy as np


def export_spinnaker2(
    net: nengo.Network, target: str = "hardware", **kwargs: object
) -> str:
    """Export a Nengo network as py-spinnaker2 code.

    Parameters
    ----------
    net : nengo.Network
        A Nengo network.

    Returns
    -------
    str
        Python code string for py-spinnaker2.
    """
    lines = [
        '"""py-spinnaker2 code — auto-generated by neurocnl."""',
        "",
        "from spinnaker2 import snn, hardware",
        "from spinnaker2 import helpers",
        "import numpy as np",
        "",
        "# Define network",
        'net = snn.Network("neurocnl_network")',
        "",
    ]

    # Create populations
    ensemble_vars = {}
    for i, ens in enumerate(net.all_ensembles):
        var_name = (ens.label or f"pop_{i}").replace(" ", "_").replace("-", "_")
        ensemble_vars[id(ens)] = var_name

        nt = ens.neuron_type

        # In SpiNNaker2, we pass a params dictionary for the LIF model
        # The exact parameter names may depend on the custom or built-in model,
        # but common ones are tau_m, tau_refrac, v_thresh, v_rest, v_reset.
        tau_m = nt.tau_rc * 1000 if isinstance(nt, nengo.LIF) else 20.0
        tau_refrac = nt.tau_ref * 1000 if isinstance(nt, nengo.LIF) else 2.0

        lines.append(f"# Population: {ens.label or var_name}")
        lines.append(f"params_{var_name} = {{")
        lines.append(f"    'tau_m': {tau_m:.1f},")
        lines.append(f"    'tau_refrac': {tau_refrac:.1f},")
        lines.append("    'v_thresh': -50.0,")
        lines.append("    'v_reset': -65.0,")
        lines.append("    'v_rest': -65.0,")
        lines.append("}")
        lines.append(f"{var_name} = snn.Population(")
        lines.append(f"    size={ens.n_neurons},")
        lines.append('    neuron_model="lif",')
        lines.append(f"    params=params_{var_name},")
        lines.append(f'    name="{ens.label or var_name}",')
        lines.append('    record=["spikes", "v"]')
        lines.append(")")
        lines.append(f"net.add({var_name})")
        lines.append("")

    # Create projections
    for i, conn in enumerate(net.all_connections):
        pre = conn.pre_obj
        post = conn.post_obj
        pre_ens = (
            pre if isinstance(pre, nengo.Ensemble) else getattr(pre, "ensemble", None)
        )
        post_ens = (
            post
            if isinstance(post, nengo.Ensemble)
            else getattr(post, "ensemble", None)
        )

        if (
            pre_ens
            and post_ens
            and id(pre_ens) in ensemble_vars
            and id(post_ens) in ensemble_vars
        ):
            pre_var = ensemble_vars[id(pre_ens)]
            post_var = ensemble_vars[id(post_ens)]

            proj_var = f"proj_{i}"
            lines.append(f"# Projection: {pre_var} -> {post_var}")
            weight_lookup = _connection_weight_lookup(
                conn, pre_ens.dimensions, post_ens.dimensions
            )
            lines.append(
                f"weight_lookup_{proj_var} = np.array({weight_lookup.tolist()}, dtype=float)"
            )
            lines.append(f"conns_{proj_var} = []")
            lines.append(f"for pre_idx in range({pre_ens.n_neurons}):")
            lines.append(f"    pre_dim = pre_idx % {max(1, pre_ens.dimensions)}")
            lines.append(f"    for post_idx in range({post_ens.n_neurons}):")
            lines.append(f"        post_dim = post_idx % {max(1, post_ens.dimensions)}")
            lines.append(
                f"        scaled_weight = int(round(weight_lookup_{proj_var}[post_dim, pre_dim] * 10))"
            )
            lines.append("        if scaled_weight == 0:")
            lines.append("            continue")
            lines.append(
                f"        conns_{proj_var}.append([pre_idx, post_idx, scaled_weight, 1])"
            )
            lines.append(
                f"connector_{proj_var} = snn.FromListConnector(conns_{proj_var})"
            )

            lines.append(f"{proj_var} = snn.Projection(")
            lines.append(f"    pre={pre_var},")
            lines.append(f"    post={post_var},")
            lines.append(f"    connector=connector_{proj_var}")
            lines.append(")")
            lines.append(f"net.add({proj_var})")
            lines.append("")

    # Run
    lines.extend(
        [
            "# Run simulation",
        ]
    )

    if target == "sim":
        lines.append("from spinnaker2 import brian2_sim")
        lines.append("hw = brian2_sim.SpiNNaker2Simulator()")
    else:
        lines.append("hw = hardware.SpiNNaker2Chip()")

    lines.extend(["timesteps = 1000", "hw.run(net, timesteps)", "", "# Retrieve data"])

    for var_name in ensemble_vars.values():
        lines.append(f"{var_name}_spikes = {var_name}.get_spikes()")
        lines.append(f"{var_name}_voltages = {var_name}.get_voltages()")

    return "\n".join(lines)


def _connection_weight_lookup(
    conn: nengo.Connection,
    pre_dimensions: int,
    post_dimensions: int,
) -> np.ndarray[Any, Any]:
    if not hasattr(conn, "transform"):
        return np.full((post_dimensions, pre_dimensions), 1.0, dtype=float)

    transform = conn.transform
    raw_weight = 1.0
    if hasattr(transform, "init"):
        raw_weight = transform.init
    else:
        raw_weight = transform

    if isinstance(transform, nengo.transforms.NoTransform):
        return np.full((post_dimensions, pre_dimensions), 1.0, dtype=float)

    if isinstance(raw_weight, int | float):
        return np.full(
            (post_dimensions, pre_dimensions), float(raw_weight), dtype=float
        )

    weight_array = np.asarray(raw_weight, dtype=float)
    if weight_array.ndim == 0:
        return np.full(
            (post_dimensions, pre_dimensions), float(weight_array), dtype=float
        )

    if weight_array.ndim == 1:
        if weight_array.size == pre_dimensions == post_dimensions:
            return np.diag(weight_array)
        if weight_array.size == post_dimensions:
            return np.repeat(weight_array[:, np.newaxis], pre_dimensions, axis=1)
        if weight_array.size == pre_dimensions:
            return np.repeat(weight_array[np.newaxis, :], post_dimensions, axis=0)
        return np.resize(weight_array, (post_dimensions, pre_dimensions))

    return np.resize(weight_array, (post_dimensions, pre_dimensions))
