// Mocks generated by Mockito 5.4.6 from annotations
// in neuro_toolkit/test/features/neurocnl/providers/studio_document_revision_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i25;
import 'dart:typed_data' as _i26;

import 'package:http/http.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i24;
import 'package:neuro_toolkit/features/neurocnl/models/canvas/pipeline_cnl_result.dart'
    as _i10;
import 'package:neuro_toolkit/features/neurocnl/models/crossbar_export.dart'
    as _i29;
import 'package:neuro_toolkit/features/neurocnl/models/crossbar_export_result.dart'
    as _i19;
import 'package:neuro_toolkit/features/neurocnl/models/dataset_catalog.dart'
    as _i3;
import 'package:neuro_toolkit/features/neurocnl/models/deploy_preview_result.dart'
    as _i7;
import 'package:neuro_toolkit/features/neurocnl/models/energy_report.dart'
    as _i20;
import 'package:neuro_toolkit/features/neurocnl/models/fault_injection_report.dart'
    as _i22;
import 'package:neuro_toolkit/features/neurocnl/models/health_status.dart'
    as _i15;
import 'package:neuro_toolkit/features/neurocnl/models/job_status.dart' as _i23;
import 'package:neuro_toolkit/features/neurocnl/models/launcher_diagnostics.dart'
    as _i16;
import 'package:neuro_toolkit/features/neurocnl/models/network_graph.dart'
    as _i8;
import 'package:neuro_toolkit/features/neurocnl/models/parsed_spec.dart' as _i4;
import 'package:neuro_toolkit/features/neurocnl/models/prosthetic_sim.dart'
    as _i17;
import 'package:neuro_toolkit/features/neurocnl/models/quantization_report.dart'
    as _i21;
import 'package:neuro_toolkit/features/neurocnl/models/sensor_frame.dart'
    as _i30;
import 'package:neuro_toolkit/features/neurocnl/models/server_workspace_summary.dart'
    as _i27;
import 'package:neuro_toolkit/features/neurocnl/models/simulation_result.dart'
    as _i11;
import 'package:neuro_toolkit/features/neurocnl/models/simulator_preflight.dart'
    as _i6;
import 'package:neuro_toolkit/features/neurocnl/models/sleep_train.dart'
    as _i18;
import 'package:neuro_toolkit/features/neurocnl/models/target_reachability.dart'
    as _i14;
import 'package:neuro_toolkit/features/neurocnl/models/template.dart' as _i28;
import 'package:neuro_toolkit/features/neurocnl/models/validation_result.dart'
    as _i5;
import 'package:neuro_toolkit/features/neurocnl/services/api_client.dart'
    as _i9;
import 'package:neuro_toolkit/features/neurocnl/services/export_artifact.dart'
    as _i13;
import 'package:neuro_toolkit/features/neurocnl/services/neurosim_import_contract.dart'
    as _i12;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeDuration_0 extends _i1.SmartFake implements Duration {
  _FakeDuration_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeClient_1 extends _i1.SmartFake implements _i2.Client {
  _FakeClient_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDatasetCatalogList_2 extends _i1.SmartFake
    implements _i3.DatasetCatalogList {
  _FakeDatasetCatalogList_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDatasetEntry_3 extends _i1.SmartFake implements _i3.DatasetEntry {
  _FakeDatasetEntry_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDatasetDownloadResult_4 extends _i1.SmartFake
    implements _i3.DatasetDownloadResult {
  _FakeDatasetDownloadResult_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeParseResult_5 extends _i1.SmartFake implements _i4.ParseResult {
  _FakeParseResult_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeValidationResult_6 extends _i1.SmartFake
    implements _i5.ValidationResult {
  _FakeValidationResult_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePreflightResult_7 extends _i1.SmartFake
    implements _i6.PreflightResult {
  _FakePreflightResult_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDeployPreviewResult_8 extends _i1.SmartFake
    implements _i7.DeployPreviewResult {
  _FakeDeployPreviewResult_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGenerateResult_9 extends _i1.SmartFake
    implements _i8.GenerateResult {
  _FakeGenerateResult_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeNotebookGenerationResult_10 extends _i1.SmartFake
    implements _i9.NotebookGenerationResult {
  _FakeNotebookGenerationResult_10(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePipelineCnlResult_11 extends _i1.SmartFake
    implements _i10.PipelineCnlResult {
  _FakePipelineCnlResult_11(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePipelineConfigParseResult_12 extends _i1.SmartFake
    implements _i10.PipelineConfigParseResult {
  _FakePipelineConfigParseResult_12(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSimulationResult_13 extends _i1.SmartFake
    implements _i11.SimulationResult {
  _FakeSimulationResult_13(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeNeurosimImportContract_14 extends _i1.SmartFake
    implements _i12.NeurosimImportContract {
  _FakeNeurosimImportContract_14(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeExportArtifact_15 extends _i1.SmartFake
    implements _i13.ExportArtifact {
  _FakeExportArtifact_15(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTargetReachability_16 extends _i1.SmartFake
    implements _i14.TargetReachability {
  _FakeTargetReachability_16(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeHealthStatus_17 extends _i1.SmartFake implements _i15.HealthStatus {
  _FakeHealthStatus_17(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLauncherDiagnostics_18 extends _i1.SmartFake
    implements _i16.LauncherDiagnostics {
  _FakeLauncherDiagnostics_18(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeProstheticSimResult_19 extends _i1.SmartFake
    implements _i17.ProstheticSimResult {
  _FakeProstheticSimResult_19(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSleepTrainResult_20 extends _i1.SmartFake
    implements _i18.SleepTrainResult {
  _FakeSleepTrainResult_20(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeActivityFetchResult_21 extends _i1.SmartFake
    implements _i9.ActivityFetchResult {
  _FakeActivityFetchResult_21(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCrossbarExportResult_22 extends _i1.SmartFake
    implements _i19.CrossbarExportResult {
  _FakeCrossbarExportResult_22(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEnergyReport_23 extends _i1.SmartFake implements _i20.EnergyReport {
  _FakeEnergyReport_23(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeQuantizationReport_24 extends _i1.SmartFake
    implements _i21.QuantizationReport {
  _FakeQuantizationReport_24(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFaultInjectionReport_25 extends _i1.SmartFake
    implements _i22.FaultInjectionReport {
  _FakeFaultInjectionReport_25(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeJobStatus_26<T1> extends _i1.SmartFake
    implements _i23.JobStatus<T1> {
  _FakeJobStatus_26(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUri_27 extends _i1.SmartFake implements Uri {
  _FakeUri_27(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiClient extends _i1.Mock implements _i9.ApiClient {
  MockApiClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get apiKey =>
      (super.noSuchMethod(
            Invocation.getter(#apiKey),
            returnValue: _i24.dummyValue<String>(
              this,
              Invocation.getter(#apiKey),
            ),
          )
          as String);

  @override
  String get baseUrl =>
      (super.noSuchMethod(
            Invocation.getter(#baseUrl),
            returnValue: _i24.dummyValue<String>(
              this,
              Invocation.getter(#baseUrl),
            ),
          )
          as String);

  @override
  Duration get timeout =>
      (super.noSuchMethod(
            Invocation.getter(#timeout),
            returnValue: _FakeDuration_0(this, Invocation.getter(#timeout)),
          )
          as Duration);

  @override
  _i2.Client get rawHttpClient =>
      (super.noSuchMethod(
            Invocation.getter(#rawHttpClient),
            returnValue: _FakeClient_1(this, Invocation.getter(#rawHttpClient)),
          )
          as _i2.Client);

  @override
  _i25.Future<_i3.DatasetCatalogList> listDatasets() =>
      (super.noSuchMethod(
            Invocation.method(#listDatasets, []),
            returnValue: _i25.Future<_i3.DatasetCatalogList>.value(
              _FakeDatasetCatalogList_2(
                this,
                Invocation.method(#listDatasets, []),
              ),
            ),
          )
          as _i25.Future<_i3.DatasetCatalogList>);

  @override
  _i25.Future<_i3.DatasetEntry> importLocalDataset({
    required String? filename,
    required _i26.Uint8List? bytes,
    String? serverPath,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#importLocalDataset, [], {
              #filename: filename,
              #bytes: bytes,
              #serverPath: serverPath,
            }),
            returnValue: _i25.Future<_i3.DatasetEntry>.value(
              _FakeDatasetEntry_3(
                this,
                Invocation.method(#importLocalDataset, [], {
                  #filename: filename,
                  #bytes: bytes,
                  #serverPath: serverPath,
                }),
              ),
            ),
          )
          as _i25.Future<_i3.DatasetEntry>);

  @override
  _i25.Future<String> uploadRawDatasetFile({
    required String? filename,
    required _i26.Uint8List? bytes,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#uploadRawDatasetFile, [], {
              #filename: filename,
              #bytes: bytes,
            }),
            returnValue: _i25.Future<String>.value(
              _i24.dummyValue<String>(
                this,
                Invocation.method(#uploadRawDatasetFile, [], {
                  #filename: filename,
                  #bytes: bytes,
                }),
              ),
            ),
          )
          as _i25.Future<String>);

  @override
  _i25.Future<bool> checkDatasetPathExists(String? path) =>
      (super.noSuchMethod(
            Invocation.method(#checkDatasetPathExists, [path]),
            returnValue: _i25.Future<bool>.value(false),
          )
          as _i25.Future<bool>);

  @override
  _i25.Future<_i3.DatasetDownloadResult> downloadDataset(String? datasetId) =>
      (super.noSuchMethod(
            Invocation.method(#downloadDataset, [datasetId]),
            returnValue: _i25.Future<_i3.DatasetDownloadResult>.value(
              _FakeDatasetDownloadResult_4(
                this,
                Invocation.method(#downloadDataset, [datasetId]),
              ),
            ),
          )
          as _i25.Future<_i3.DatasetDownloadResult>);

  @override
  _i25.Future<String> triggerAndWaitForDownload(String? datasetId) =>
      (super.noSuchMethod(
            Invocation.method(#triggerAndWaitForDownload, [datasetId]),
            returnValue: _i25.Future<String>.value(
              _i24.dummyValue<String>(
                this,
                Invocation.method(#triggerAndWaitForDownload, [datasetId]),
              ),
            ),
          )
          as _i25.Future<String>);

  @override
  _i25.Future<_i4.ParseResult> parse(String? spec) =>
      (super.noSuchMethod(
            Invocation.method(#parse, [spec]),
            returnValue: _i25.Future<_i4.ParseResult>.value(
              _FakeParseResult_5(this, Invocation.method(#parse, [spec])),
            ),
          )
          as _i25.Future<_i4.ParseResult>);

  @override
  _i25.Future<_i5.ValidationResult> validate(
    String? spec, {
    Map<String, dynamic>? params,
    String? backend = 'nir',
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #validate,
              [spec],
              {#params: params, #backend: backend},
            ),
            returnValue: _i25.Future<_i5.ValidationResult>.value(
              _FakeValidationResult_6(
                this,
                Invocation.method(
                  #validate,
                  [spec],
                  {#params: params, #backend: backend},
                ),
              ),
            ),
          )
          as _i25.Future<_i5.ValidationResult>);

  @override
  _i25.Future<_i6.PreflightResult> preflight(
    String? spec,
    String? backendName,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#preflight, [spec, backendName]),
            returnValue: _i25.Future<_i6.PreflightResult>.value(
              _FakePreflightResult_7(
                this,
                Invocation.method(#preflight, [spec, backendName]),
              ),
            ),
          )
          as _i25.Future<_i6.PreflightResult>);

  @override
  _i25.Future<_i6.PreflightResult> preflightNir(
    _i26.Uint8List? nirBytes,
    String? backendName,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#preflightNir, [nirBytes, backendName]),
            returnValue: _i25.Future<_i6.PreflightResult>.value(
              _FakePreflightResult_7(
                this,
                Invocation.method(#preflightNir, [nirBytes, backendName]),
              ),
            ),
          )
          as _i25.Future<_i6.PreflightResult>);

  @override
  _i25.Future<List<_i7.DeployTargetInfo>> getDeployTargets() =>
      (super.noSuchMethod(
            Invocation.method(#getDeployTargets, []),
            returnValue: _i25.Future<List<_i7.DeployTargetInfo>>.value(
              <_i7.DeployTargetInfo>[],
            ),
          )
          as _i25.Future<List<_i7.DeployTargetInfo>>);

  @override
  _i25.Future<_i7.DeployPreviewResult> previewDeployTarget(
    String? spec,
    String? target,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#previewDeployTarget, [spec, target]),
            returnValue: _i25.Future<_i7.DeployPreviewResult>.value(
              _FakeDeployPreviewResult_8(
                this,
                Invocation.method(#previewDeployTarget, [spec, target]),
              ),
            ),
          )
          as _i25.Future<_i7.DeployPreviewResult>);

  @override
  _i25.Future<_i8.GenerateResult> generate(
    String? spec, {
    Map<String, dynamic>? params,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#generate, [spec], {#params: params}),
            returnValue: _i25.Future<_i8.GenerateResult>.value(
              _FakeGenerateResult_9(
                this,
                Invocation.method(#generate, [spec], {#params: params}),
              ),
            ),
          )
          as _i25.Future<_i8.GenerateResult>);

  @override
  _i25.Future<_i9.NotebookGenerationResult> generateNotebookV2({
    required String? spec,
    required Map<String, dynamic>? pipelineConfig,
    Map<String, dynamic>? pipelinePhases,
    String? pipelineCnl,
    String? workspacePath = '',
    String? importId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#generateNotebookV2, [], {
              #spec: spec,
              #pipelineConfig: pipelineConfig,
              #pipelinePhases: pipelinePhases,
              #pipelineCnl: pipelineCnl,
              #workspacePath: workspacePath,
              #importId: importId,
            }),
            returnValue: _i25.Future<_i9.NotebookGenerationResult>.value(
              _FakeNotebookGenerationResult_10(
                this,
                Invocation.method(#generateNotebookV2, [], {
                  #spec: spec,
                  #pipelineConfig: pipelineConfig,
                  #pipelinePhases: pipelinePhases,
                  #pipelineCnl: pipelineCnl,
                  #workspacePath: workspacePath,
                  #importId: importId,
                }),
              ),
            ),
          )
          as _i25.Future<_i9.NotebookGenerationResult>);

  @override
  _i25.Future<_i9.NotebookGenerationResult> generateAkidaMnistNotebook({
    required String? workspacePath,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#generateAkidaMnistNotebook, [], {
              #workspacePath: workspacePath,
            }),
            returnValue: _i25.Future<_i9.NotebookGenerationResult>.value(
              _FakeNotebookGenerationResult_10(
                this,
                Invocation.method(#generateAkidaMnistNotebook, [], {
                  #workspacePath: workspacePath,
                }),
              ),
            ),
          )
          as _i25.Future<_i9.NotebookGenerationResult>);

  @override
  _i25.Future<Map<String, dynamic>> latestAkidaBundle(
    String? workspaceFolder,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#latestAkidaBundle, [workspaceFolder]),
            returnValue: _i25.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i25.Future<Map<String, dynamic>>);

  @override
  _i25.Future<Map<String, dynamic>> latestTrainedNir(String? workspaceFolder) =>
      (super.noSuchMethod(
            Invocation.method(#latestTrainedNir, [workspaceFolder]),
            returnValue: _i25.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i25.Future<Map<String, dynamic>>);

  @override
  _i25.Future<Map<String, dynamic>> datasetSample(
    String? workspaceFolder, {
    int? index = 0,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #datasetSample,
              [workspaceFolder],
              {#index: index},
            ),
            returnValue: _i25.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i25.Future<Map<String, dynamic>>);

  @override
  _i25.Future<_i10.PipelineCnlResult> generatePipelineCnl(
    Map<String, dynamic>? pipelineConfig,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#generatePipelineCnl, [pipelineConfig]),
            returnValue: _i25.Future<_i10.PipelineCnlResult>.value(
              _FakePipelineCnlResult_11(
                this,
                Invocation.method(#generatePipelineCnl, [pipelineConfig]),
              ),
            ),
          )
          as _i25.Future<_i10.PipelineCnlResult>);

  @override
  _i25.Future<_i10.PipelineConfigParseResult> parsePipelineCnl(
    String? cnlText,
    Map<String, dynamic>? currentPipelineConfig,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#parsePipelineCnl, [
              cnlText,
              currentPipelineConfig,
            ]),
            returnValue: _i25.Future<_i10.PipelineConfigParseResult>.value(
              _FakePipelineConfigParseResult_12(
                this,
                Invocation.method(#parsePipelineCnl, [
                  cnlText,
                  currentPipelineConfig,
                ]),
              ),
            ),
          )
          as _i25.Future<_i10.PipelineConfigParseResult>);

  @override
  _i25.Future<String> ensureWorkspace({required String? workspacePath}) =>
      (super.noSuchMethod(
            Invocation.method(#ensureWorkspace, [], {
              #workspacePath: workspacePath,
            }),
            returnValue: _i25.Future<String>.value(
              _i24.dummyValue<String>(
                this,
                Invocation.method(#ensureWorkspace, [], {
                  #workspacePath: workspacePath,
                }),
              ),
            ),
          )
          as _i25.Future<String>);

  @override
  _i25.Future<void> syncWorkspace({
    required String? slug,
    required String? name,
    required Map<String, dynamic>? config,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#syncWorkspace, [], {
              #slug: slug,
              #name: name,
              #config: config,
            }),
            returnValue: _i25.Future<void>.value(),
            returnValueForMissingStub: _i25.Future<void>.value(),
          )
          as _i25.Future<void>);

  @override
  _i25.Future<List<_i27.ServerWorkspaceSummary>> listServerWorkspaces() =>
      (super.noSuchMethod(
            Invocation.method(#listServerWorkspaces, []),
            returnValue: _i25.Future<List<_i27.ServerWorkspaceSummary>>.value(
              <_i27.ServerWorkspaceSummary>[],
            ),
          )
          as _i25.Future<List<_i27.ServerWorkspaceSummary>>);

  @override
  _i25.Future<Map<String, dynamic>> getServerWorkspace(String? slug) =>
      (super.noSuchMethod(
            Invocation.method(#getServerWorkspace, [slug]),
            returnValue: _i25.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i25.Future<Map<String, dynamic>>);

  @override
  _i25.Future<Map<String, bool>> getTargetAvailability() =>
      (super.noSuchMethod(
            Invocation.method(#getTargetAvailability, []),
            returnValue: _i25.Future<Map<String, bool>>.value(<String, bool>{}),
          )
          as _i25.Future<Map<String, bool>>);

  @override
  _i25.Future<double?> getNotebookLastModified({
    required String? workspaceFolder,
    required String? filename,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getNotebookLastModified, [], {
              #workspaceFolder: workspaceFolder,
              #filename: filename,
            }),
            returnValue: _i25.Future<double?>.value(),
          )
          as _i25.Future<double?>);

  @override
  _i25.Future<_i11.SimulationResult> simulate(
    String? spec, {
    double? duration = 1.0,
    double? dt = 0.001,
    Map<String, dynamic>? params,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #simulate,
              [spec],
              {#duration: duration, #dt: dt, #params: params},
            ),
            returnValue: _i25.Future<_i11.SimulationResult>.value(
              _FakeSimulationResult_13(
                this,
                Invocation.method(
                  #simulate,
                  [spec],
                  {#duration: duration, #dt: dt, #params: params},
                ),
              ),
            ),
          )
          as _i25.Future<_i11.SimulationResult>);

  @override
  _i25.Future<List<_i28.CnlTemplate>> getTemplates() =>
      (super.noSuchMethod(
            Invocation.method(#getTemplates, []),
            returnValue: _i25.Future<List<_i28.CnlTemplate>>.value(
              <_i28.CnlTemplate>[],
            ),
          )
          as _i25.Future<List<_i28.CnlTemplate>>);

  @override
  _i25.Future<_i12.NeurosimImportContract> prepareNeurosimHandoff(
    String? spec,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#prepareNeurosimHandoff, [spec]),
            returnValue: _i25.Future<_i12.NeurosimImportContract>.value(
              _FakeNeurosimImportContract_14(
                this,
                Invocation.method(#prepareNeurosimHandoff, [spec]),
              ),
            ),
          )
          as _i25.Future<_i12.NeurosimImportContract>);

  @override
  _i25.Future<String> export(
    String? spec, {
    String? format = 'cnl',
    String? filename = 'spec.cnl',
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #export,
              [spec],
              {#format: format, #filename: filename},
            ),
            returnValue: _i25.Future<String>.value(
              _i24.dummyValue<String>(
                this,
                Invocation.method(
                  #export,
                  [spec],
                  {#format: format, #filename: filename},
                ),
              ),
            ),
          )
          as _i25.Future<String>);

  @override
  _i25.Future<_i13.ExportArtifact> exportNirArtifact(
    String? spec, {
    String? filename = 'network.nir',
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #exportNirArtifact,
              [spec],
              {#filename: filename},
            ),
            returnValue: _i25.Future<_i13.ExportArtifact>.value(
              _FakeExportArtifact_15(
                this,
                Invocation.method(
                  #exportNirArtifact,
                  [spec],
                  {#filename: filename},
                ),
              ),
            ),
          )
          as _i25.Future<_i13.ExportArtifact>);

  @override
  _i25.Future<_i14.TargetReachability> getTargetReachability(
    String? targetId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getTargetReachability, [targetId]),
            returnValue: _i25.Future<_i14.TargetReachability>.value(
              _FakeTargetReachability_16(
                this,
                Invocation.method(#getTargetReachability, [targetId]),
              ),
            ),
          )
          as _i25.Future<_i14.TargetReachability>);

  @override
  _i25.Future<_i15.HealthStatus> health() =>
      (super.noSuchMethod(
            Invocation.method(#health, []),
            returnValue: _i25.Future<_i15.HealthStatus>.value(
              _FakeHealthStatus_17(this, Invocation.method(#health, [])),
            ),
          )
          as _i25.Future<_i15.HealthStatus>);

  @override
  _i25.Future<_i16.LauncherDiagnostics> fetchLauncherDiagnostics() =>
      (super.noSuchMethod(
            Invocation.method(#fetchLauncherDiagnostics, []),
            returnValue: _i25.Future<_i16.LauncherDiagnostics>.value(
              _FakeLauncherDiagnostics_18(
                this,
                Invocation.method(#fetchLauncherDiagnostics, []),
              ),
            ),
          )
          as _i25.Future<_i16.LauncherDiagnostics>);

  @override
  _i25.Future<_i17.ProstheticSimResult> prostheticSimulate(
    _i17.ProstheticSimRequest? req,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#prostheticSimulate, [req]),
            returnValue: _i25.Future<_i17.ProstheticSimResult>.value(
              _FakeProstheticSimResult_19(
                this,
                Invocation.method(#prostheticSimulate, [req]),
              ),
            ),
          )
          as _i25.Future<_i17.ProstheticSimResult>);

  @override
  _i25.Future<_i18.SleepTrainResult> prostheticSleep(
    _i18.SleepTrainRequest? req,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#prostheticSleep, [req]),
            returnValue: _i25.Future<_i18.SleepTrainResult>.value(
              _FakeSleepTrainResult_20(
                this,
                Invocation.method(#prostheticSleep, [req]),
              ),
            ),
          )
          as _i25.Future<_i18.SleepTrainResult>);

  @override
  _i25.Future<Map<String, dynamic>> compareActivity(
    List<Map<String, String>>? jobs, {
    String? layer = 'hidden_spikes',
  }) =>
      (super.noSuchMethod(
            Invocation.method(#compareActivity, [jobs], {#layer: layer}),
            returnValue: _i25.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i25.Future<Map<String, dynamic>>);

  @override
  _i25.Future<_i9.ActivityFetchResult> getTrainingActivityNpy(
    String? jobId, {
    int? epoch,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getTrainingActivityNpy,
              [jobId],
              {#epoch: epoch},
            ),
            returnValue: _i25.Future<_i9.ActivityFetchResult>.value(
              _FakeActivityFetchResult_21(
                this,
                Invocation.method(
                  #getTrainingActivityNpy,
                  [jobId],
                  {#epoch: epoch},
                ),
              ),
            ),
          )
          as _i25.Future<_i9.ActivityFetchResult>);

  @override
  _i25.Future<_i26.Uint8List?> getVisualizationImage(
    String? jobId,
    String? imageKey,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getVisualizationImage, [jobId, imageKey]),
            returnValue: _i25.Future<_i26.Uint8List?>.value(),
          )
          as _i25.Future<_i26.Uint8List?>);

  @override
  _i25.Future<_i19.CrossbarExportResult> prostheticExportCrossbar(
    _i29.CrossbarExportRequest? req,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#prostheticExportCrossbar, [req]),
            returnValue: _i25.Future<_i19.CrossbarExportResult>.value(
              _FakeCrossbarExportResult_22(
                this,
                Invocation.method(#prostheticExportCrossbar, [req]),
              ),
            ),
          )
          as _i25.Future<_i19.CrossbarExportResult>);

  @override
  _i25.Future<_i20.EnergyReport> prostheticEnergy(String? spec) =>
      (super.noSuchMethod(
            Invocation.method(#prostheticEnergy, [spec]),
            returnValue: _i25.Future<_i20.EnergyReport>.value(
              _FakeEnergyReport_23(
                this,
                Invocation.method(#prostheticEnergy, [spec]),
              ),
            ),
          )
          as _i25.Future<_i20.EnergyReport>);

  @override
  _i25.Future<_i21.QuantizationReport> prostheticQuantize(
    String? spec,
    List<int>? bits,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#prostheticQuantize, [spec, bits]),
            returnValue: _i25.Future<_i21.QuantizationReport>.value(
              _FakeQuantizationReport_24(
                this,
                Invocation.method(#prostheticQuantize, [spec, bits]),
              ),
            ),
          )
          as _i25.Future<_i21.QuantizationReport>);

  @override
  _i25.Future<_i22.FaultInjectionReport> prostheticFaultInjection(
    String? spec,
    double? errorRate,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#prostheticFaultInjection, [spec, errorRate]),
            returnValue: _i25.Future<_i22.FaultInjectionReport>.value(
              _FakeFaultInjectionReport_25(
                this,
                Invocation.method(#prostheticFaultInjection, [spec, errorRate]),
              ),
            ),
          )
          as _i25.Future<_i22.FaultInjectionReport>);

  @override
  _i25.Future<Map<String, dynamic>> getTeensyNetworkPayload(
    String? spec, {
    int? bitWidth = 8,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getTeensyNetworkPayload,
              [spec],
              {#bitWidth: bitWidth},
            ),
            returnValue: _i25.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i25.Future<Map<String, dynamic>>);

  @override
  _i25.Future<Map<String, dynamic>> deployToNeurochip(
    String? spec, {
    int? bitWidth = 8,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #deployToNeurochip,
              [spec],
              {#bitWidth: bitWidth},
            ),
            returnValue: _i25.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i25.Future<Map<String, dynamic>>);

  @override
  _i25.Future<Map<String, dynamic>> getPynqDeployability(
    String? spec, {
    int? bitWidth = 8,
    String? trainedNirBase64,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getPynqDeployability,
              [spec],
              {#bitWidth: bitWidth, #trainedNirBase64: trainedNirBase64},
            ),
            returnValue: _i25.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i25.Future<Map<String, dynamic>>);

  @override
  _i25.Future<Map<String, dynamic>> getAkidaDeployability(
    String? spec, {
    int? bitWidth = 4,
    String? akidaVersion = 'akida1',
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getAkidaDeployability,
              [spec],
              {#bitWidth: bitWidth, #akidaVersion: akidaVersion},
            ),
            returnValue: _i25.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i25.Future<Map<String, dynamic>>);

  @override
  _i25.Future<Map<String, dynamic>> getLavaDeployability(
    String? spec, {
    int? bitWidth = 8,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getLavaDeployability,
              [spec],
              {#bitWidth: bitWidth},
            ),
            returnValue: _i25.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i25.Future<Map<String, dynamic>>);

  @override
  _i25.Future<Map<String, dynamic>> checkScNeuroCoreToolchain(
    String? toolchain, {
    String? binPath,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #checkScNeuroCoreToolchain,
              [toolchain],
              {#binPath: binPath},
            ),
            returnValue: _i25.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i25.Future<Map<String, dynamic>>);

  @override
  _i25.Future<List<String>> listSerialPorts() =>
      (super.noSuchMethod(
            Invocation.method(#listSerialPorts, []),
            returnValue: _i25.Future<List<String>>.value(<String>[]),
          )
          as _i25.Future<List<String>>);

  @override
  _i25.Future<void> connectHardware(String? port, int? baudRate) =>
      (super.noSuchMethod(
            Invocation.method(#connectHardware, [port, baudRate]),
            returnValue: _i25.Future<void>.value(),
            returnValueForMissingStub: _i25.Future<void>.value(),
          )
          as _i25.Future<void>);

  @override
  _i25.Future<void> disconnectHardware() =>
      (super.noSuchMethod(
            Invocation.method(#disconnectHardware, []),
            returnValue: _i25.Future<void>.value(),
            returnValueForMissingStub: _i25.Future<void>.value(),
          )
          as _i25.Future<void>);

  @override
  _i25.Stream<_i30.SensorFrame> streamHardwareSensorData() =>
      (super.noSuchMethod(
            Invocation.method(#streamHardwareSensorData, []),
            returnValue: _i25.Stream<_i30.SensorFrame>.empty(),
          )
          as _i25.Stream<_i30.SensorFrame>);

  @override
  _i25.Future<_i23.JobStatus<T>> getJobStatus<T>(
    String? jobId, {
    T Function(Map<String, dynamic>)? fromJsonT,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getJobStatus, [jobId], {#fromJsonT: fromJsonT}),
            returnValue: _i25.Future<_i23.JobStatus<T>>.value(
              _FakeJobStatus_26<T>(
                this,
                Invocation.method(
                  #getJobStatus,
                  [jobId],
                  {#fromJsonT: fromJsonT},
                ),
              ),
            ),
          )
          as _i25.Future<_i23.JobStatus<T>>);

  @override
  _i25.Stream<Map<String, dynamic>> streamTrainingEvents(String? jobId) =>
      (super.noSuchMethod(
            Invocation.method(#streamTrainingEvents, [jobId]),
            returnValue: _i25.Stream<Map<String, dynamic>>.empty(),
          )
          as _i25.Stream<Map<String, dynamic>>);

  @override
  _i25.Future<String> runNotebook({
    required String? notebookPath,
    required String? platform,
    String? kernelName,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#runNotebook, [], {
              #notebookPath: notebookPath,
              #platform: platform,
              #kernelName: kernelName,
            }),
            returnValue: _i25.Future<String>.value(
              _i24.dummyValue<String>(
                this,
                Invocation.method(#runNotebook, [], {
                  #notebookPath: notebookPath,
                  #platform: platform,
                  #kernelName: kernelName,
                }),
              ),
            ),
          )
          as _i25.Future<String>);

  @override
  _i25.Future<List<Map<String, dynamic>>> getActiveNotebookJobs() =>
      (super.noSuchMethod(
            Invocation.method(#getActiveNotebookJobs, []),
            returnValue: _i25.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i25.Future<List<Map<String, dynamic>>>);

  @override
  _i25.Future<void> cancelNotebookJob(String? jobId) =>
      (super.noSuchMethod(
            Invocation.method(#cancelNotebookJob, [jobId]),
            returnValue: _i25.Future<void>.value(),
            returnValueForMissingStub: _i25.Future<void>.value(),
          )
          as _i25.Future<void>);

  @override
  _i25.Future<List<Map<String, dynamic>>> getJupyterSessions() =>
      (super.noSuchMethod(
            Invocation.method(#getJupyterSessions, []),
            returnValue: _i25.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i25.Future<List<Map<String, dynamic>>>);

  @override
  _i25.Future<void> stopJupyterSession(String? sessionId) =>
      (super.noSuchMethod(
            Invocation.method(#stopJupyterSession, [sessionId]),
            returnValue: _i25.Future<void>.value(),
            returnValueForMissingStub: _i25.Future<void>.value(),
          )
          as _i25.Future<void>);

  @override
  _i25.Future<String?> getJupyterUrl() =>
      (super.noSuchMethod(
            Invocation.method(#getJupyterUrl, []),
            returnValue: _i25.Future<String?>.value(),
          )
          as _i25.Future<String?>);

  @override
  Uri buildUri(String? path, {Map<String, String>? queryParameters}) =>
      (super.noSuchMethod(
            Invocation.method(
              #buildUri,
              [path],
              {#queryParameters: queryParameters},
            ),
            returnValue: _FakeUri_27(
              this,
              Invocation.method(
                #buildUri,
                [path],
                {#queryParameters: queryParameters},
              ),
            ),
          )
          as Uri);

  @override
  dynamic decodeBody(_i2.Response? response) =>
      super.noSuchMethod(Invocation.method(#decodeBody, [response]));

  @override
  Map<String, dynamic> decodeBodyAsMap(_i2.Response? response) =>
      (super.noSuchMethod(
            Invocation.method(#decodeBodyAsMap, [response]),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  List<dynamic> decodeBodyAsList(_i2.Response? response) =>
      (super.noSuchMethod(
            Invocation.method(#decodeBodyAsList, [response]),
            returnValue: <dynamic>[],
          )
          as List<dynamic>);

  @override
  _i25.Future<Map<String, dynamic>> baseGet(
    String? path, {
    String? apiKey = '',
    Exception Function(int, String)? errorFactory,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #baseGet,
              [path],
              {#apiKey: apiKey, #errorFactory: errorFactory},
            ),
            returnValue: _i25.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i25.Future<Map<String, dynamic>>);

  @override
  _i25.Future<Map<String, dynamic>> basePost(
    String? path,
    Map<String, dynamic>? body, {
    String? apiKey = '',
    Exception Function(int, String)? errorFactory,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #basePost,
              [path, body],
              {#apiKey: apiKey, #errorFactory: errorFactory},
            ),
            returnValue: _i25.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i25.Future<Map<String, dynamic>>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}
