import 'dart:async';
import 'dart:convert';
import 'dart:io';

import 'package:crypto/crypto.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:http/http.dart' as http;

import 'package:neuro_toolkit/features/neurocnl/features/studio/workflow/steps/run_step_logic.dart';
import 'package:neuro_toolkit/features/neurocnl/models/canvas/pipeline_dag.dart';
import 'package:neuro_toolkit/features/neurocnl/models/studio_result_session.dart';
import 'package:neuro_toolkit/features/neurocnl/models/workspace_file.dart';
import 'package:neuro_toolkit/features/neurocnl/services/api_client.dart';
import 'package:neuro_toolkit/features/neurocnl/services/dataset_generation_preparer.dart';
import 'package:neuro_toolkit/features/neurocnl/services/notebook_generate_service.dart';
import 'package:neuro_toolkit/features/neurocnl/utils/canvas_projection_utils.dart';
import 'package:neuro_toolkit/features/neurocnl/providers/api_provider.dart';
import 'package:neuro_toolkit/features/neurocnl/providers/canvas/canvas_provider.dart';
import 'package:neuro_toolkit/features/neurocnl/providers/nir_import_provider.dart';
import 'package:neuro_toolkit/features/neurocnl/providers/notebook_meta_provider.dart';
import 'package:neuro_toolkit/features/neurocnl/providers/running_notebook_tasks_provider.dart';
import 'package:neuro_toolkit/features/neurocnl/providers/spec_provider.dart';
import 'package:neuro_toolkit/features/neurocnl/providers/studio_result_session_provider.dart';
import 'package:neuro_toolkit/features/neurocnl/providers/training_history_provider.dart';
import 'package:neuro_toolkit/features/neurocnl/providers/training_job_ids_provider.dart';
import 'package:neuro_toolkit/features/neurocnl/providers/training_mode_provider.dart';
import 'package:neuro_toolkit/features/neurocnl/providers/training_provider.dart';
import 'package:neuro_toolkit/features/neurocnl/providers/workspace_provider.dart';

/// What to do about a notebook that was edited (e.g. live in the embedded
/// JupyterLab view) since it was last generated by a run.
enum NotebookEditChoice { keepEdits, cancelled, discardAndRegenerate }

String slugifyWorkspaceName(String name) => name
    .toLowerCase()
    .replaceAll(RegExp(r'[^a-z0-9]+'), '-')
    .replaceAll(RegExp(r'^-+|-+$'), '');

/// Transport-level SSE/socket failures that can happen when the OS suspends
/// the app — not evidence that the server-side job failed.
bool isRecoverableTrainingStreamError(Object error) {
  if (error is ApiException) return false;
  if (error is http.ClientException) return true;
  if (error is SocketException || error is IOException) return true;
  if (error is TimeoutException) return true;
  final message = error.toString().toLowerCase();
  return message.contains('connection closed') ||
      message.contains('connection reset') ||
      message.contains('broken pipe');
}

bool _isActiveJobStatus(String status) =>
    status == 'queued' || status == 'running';

/// Orchestrates the Run step's job lifecycle: reattaching to server-side
/// jobs, starting a run across every selected platform, and streaming
/// progress for each.
///
/// Deliberately does not own any dialogs (notebook-edit confirmation,
/// manual-session-stop confirmation) — those need a `BuildContext` and stay
/// in the widget, which passes their results in as callbacks.
final trainingRunControllerProvider =
    NotifierProvider<TrainingRunController, void>(TrainingRunController.new);

class TrainingRunController extends Notifier<void> {
  final Map<String, StreamSubscription<Map<String, dynamic>>> _subscriptions =
      {};

  @override
  void build() {
    ref.onDispose(() {
      for (final sub in _subscriptions.values) {
        sub.cancel();
      }
      _subscriptions.clear();
    });
  }

  /// Looks for a job already running server-side for this workspace (e.g.
  /// started from a different GUI/device) and reattaches to it so progress
  /// isn't lost just because this GUI instance wasn't the one watching.
  Future<void> checkForReattachableJobs() async {
    final api = ref.read(apiClientProvider);
    final workspace = ref.read(workspaceProvider);
    final folder = slugifyWorkspaceName(workspace.workspaceName);
    final platforms = workspace.selectedPlatforms.isEmpty
        ? const ['snntorch_sim']
        : workspace.selectedPlatforms;

    List<Map<String, dynamic>> jobs;
    try {
      jobs = await api.getActiveNotebookJobs();
    } catch (_) {
      // Best-effort: a failure here just means reattach doesn't happen, not
      // that the run itself is broken.
      return;
    }

    final matchesByPlatform = <String, List<Map<String, dynamic>>>{};
    for (final job in jobs) {
      final notebookPath = job['notebook_path'] as String? ?? '';
      final platform = job['platform'] as String? ?? '';
      if (!notebookPath.startsWith('$folder/')) continue;
      if (!platforms.contains(platform)) continue;
      (matchesByPlatform[platform] ??= []).add(job);
    }

    final reattachable = <String, String>{};
    for (final platform in platforms) {
      final matches = matchesByPlatform[platform];
      if (matches == null || matches.length != 1) continue;
      reattachable[platform] = matches.first['job_id'] as String;
    }
    if (reattachable.isEmpty) return;
    if (ref.read(studioResultSessionProvider).phase !=
        StudioResultSessionPhase.idle) {
      return;
    }
    ref
        .read(studioResultSessionProvider.notifier)
        .beginAttempt(
          platforms: reattachable.keys,
          provenance: StudioResultProvenance(
            workspaceName: workspace.workspaceName,
            modelFingerprint: 'reattached',
          ),
        );
    final attemptId = ref.read(studioResultSessionProvider).attemptId!;
    for (final entry in reattachable.entries) {
      _reattachToJob(entry.key, entry.value, attemptId);
    }
  }

  void _reattachToJob(String platform, String jobId, String attemptId) {
    ref.read(studioResultSessionProvider.notifier).registerJob(platform, jobId);
    ref.read(trainingJobIdsProvider.notifier).setJobId(platform, jobId);
    subscribeToJob(platform, jobId, attemptId);
  }

  /// Whether a manually-started JupyterLab kernel (e.g. from "Open Notebook")
  /// is already running against [notebookPath]. The backend stops such a
  /// session itself before a Play-triggered run (they'd otherwise
  /// resource-contend and the run would silently stall for the full 30-minute
  /// timeout) — this check is only so the user gets a heads-up first, not the
  /// safety mechanism itself. Best-effort: a failure here shouldn't block Play.
  Future<bool> hasExecutingManualSession(
    ApiClient api,
    String notebookPath,
  ) async {
    try {
      final sessions = await api.getJupyterSessions();
      return hasExecutingJupyterSessionForPath(sessions, notebookPath);
    } catch (_) {
      return false;
    }
  }

  /// If the notebook generated in the Notebook step was edited since (e.g.
  /// live in the embedded JupyterLab view), asks [confirmEditChoice] (which
  /// must show a dialog and return the user's choice) before regenerating it
  /// out from under those edits. Returns null if there's nothing to ask about
  /// (no edit detected, or no generation record for this platform yet).
  Future<NotebookEditChoice?> checkForEditedNotebook(
    ApiClient api,
    String platform, {
    required Future<NotebookEditChoice> Function() confirmEditChoice,
  }) async {
    final meta = ref.read(notebookMetaProvider.notifier).forPlatform(platform);
    if (meta == null) return null;
    double? currentLastModified;
    try {
      currentLastModified = await api.getNotebookLastModified(
        workspaceFolder: meta.workspaceFolder,
        filename: meta.filename,
      );
    } catch (_) {
      // Status check failing shouldn't block a run — fall through to the
      // normal regenerate-then-run flow.
      return null;
    }
    // Small epsilon absorbs the gap between the generation write and the
    // mirror write completing.
    const epsilonSeconds = 1.5;
    final editedSinceGeneration =
        currentLastModified != null &&
        currentLastModified > meta.generatedAt + epsilonSeconds;
    if (!editedSinceGeneration) return null;
    return confirmEditChoice();
  }

  /// Starts a fresh run across every platform selected in the workspace.
  ///
  /// Returns the resolved platform list on success, so the caller can update
  /// its own "active platform tab" UI state, or null if the attempt was
  /// itself superseded mid-flight (a newer [startTraining] call started).
  Future<List<String>?> startTraining({
    required Future<NotebookEditChoice> Function() confirmEditChoice,
    required Future<bool> Function() confirmStopManualSession,
  }) async {
    final api = ref.read(apiClientProvider);
    final workspace = ref.read(workspaceProvider);
    final spec = ref.read(specTextProvider);
    final canvas = ref.read(canvasProvider);
    final platforms = workspace.selectedPlatforms.isEmpty
        ? const ['snntorch_sim']
        : workspace.selectedPlatforms;

    cancelSubscriptions();

    final resultSession = ref.read(studioResultSessionProvider.notifier)
      ..beginAttempt(
        platforms: platforms,
        provenance: StudioResultProvenance(
          workspaceName: workspace.workspaceName,
          modelFingerprint: sha256.convert(utf8.encode(spec)).toString(),
        ),
      );
    final attemptId = ref.read(studioResultSessionProvider).attemptId!;

    // Reset history for a fresh run.
    ref.read(trainingHistoryProvider.notifier).reset();
    ref.read(trainingJobIdsProvider.notifier).reset();

    final editChoices = <String, NotebookEditChoice?>{};
    for (final platform in platforms) {
      editChoices[platform] = await checkForEditedNotebook(
        api,
        platform,
        confirmEditChoice: confirmEditChoice,
      );
      if (!resultSession.isCurrentAttempt(attemptId)) return null;
    }

    final regeneratePlatforms = platforms
        .where(
          (platform) => RunStepLogic.shouldPrepareDatasets(
            keepEditedNotebook:
                editChoices[platform] == NotebookEditChoice.keepEdits,
            cancelled: editChoices[platform] == NotebookEditChoice.cancelled,
          ),
        )
        .toList(growable: false);
    Map<String, dynamic>? preparedPhases;
    if (regeneratePlatforms.isNotEmpty) {
      try {
        final preparation = await DatasetGenerationPreparer(
          apiClient: api,
        ).prepare(canvas.pipelinePhases);
        preparedPhases = preparation.phases;
        // Same remap DatasetGenerationPreparer callers apply via
        // applyDatasetUploadRemaps — inlined because that helper takes a
        // WidgetRef, which a Notifier's Ref is not.
        final canvasNotifier = ref.read(canvasProvider.notifier);
        for (final remap in preparation.uploads) {
          canvasNotifier
              .updatePipelineDagNodeParams(remap.phase, remap.nodeId, {
                'dataset_path': remap.serverPath,
                kDatasetPathScopeKey: kServerDatasetPathScope,
              });
        }
      } catch (error, stackTrace) {
        if (!resultSession.isCurrentAttempt(attemptId)) return null;
        for (final platform in regeneratePlatforms) {
          setErrorState(platform, error, stackTrace, attemptId);
        }
      }
    }

    for (final platform in platforms) {
      if (!resultSession.isCurrentAttempt(attemptId)) return null;
      final editChoice = editChoices[platform];
      if (editChoice == NotebookEditChoice.cancelled) {
        resultSession.markCancelled(platform);
        continue;
      }
      if (editChoice != NotebookEditChoice.keepEdits &&
          preparedPhases == null) {
        continue;
      }
      unawaited(
        runSinglePlatform(
          api,
          workspace,
          canvas,
          spec,
          platform,
          attemptId: attemptId,
          editChoice: editChoice,
          preparedPipelinePhases: preparedPhases,
          confirmStopManualSession: confirmStopManualSession,
        ),
      );
    }
    return platforms;
  }

  /// Runs [platform], optionally confirming with the user (via
  /// [confirmStopManualSession], which must show a dialog and return the
  /// user's choice) when a manual notebook session would be stopped.
  Future<void> runSinglePlatform(
    ApiClient api,
    WorkspaceState workspace,
    CanvasState canvas,
    String spec,
    String platform, {
    required String attemptId,
    required NotebookEditChoice? editChoice,
    required Map<String, dynamic>? preparedPipelinePhases,
    required Future<bool> Function() confirmStopManualSession,
  }) async {
    try {
      String notebookPath;
      if (editChoice == NotebookEditChoice.keepEdits) {
        final meta = ref
            .read(notebookMetaProvider.notifier)
            .forPlatform(platform)!;
        notebookPath = '${meta.workspaceFolder}/${meta.filename}';
      } else {
        final pipelineJson =
            canvas.pipeline.toJson() as Map<String, dynamic>? ?? {};
        final configJson = <String, dynamic>{
          ...pipelineJson,
          'framework': platform,
          if (workspace.selectedDataset != null)
            'dataset': workspace.selectedDataset!,
        };
        final importId = NotebookGenerateService.importIdForNotebook(
          nirImportState: ref.read(nirImportProvider),
          retainedFileBackedImportId: ref.read(
            latestFileBackedNirImportIdProvider,
          ),
        );
        final result = await api.generateNotebookV2(
          spec: spec,
          pipelineConfig: configJson,
          pipelinePhases: preparedPipelinePhases,
          workspacePath: slugifyWorkspaceName(workspace.workspaceName),
          importId: importId.isNotEmpty ? importId : null,
        );
        if (!ref
            .read(studioResultSessionProvider.notifier)
            .isCurrentAttempt(attemptId)) {
          return;
        }

        if (result.notebookFilenames.isEmpty) {
          setErrorState(
            platform,
            'Failed to generate notebook: No filenames returned.',
            null,
            attemptId,
          );
          return;
        }

        notebookPath =
            '${result.workspaceFolder}/${result.notebookFilenames.first}';
        ref
            .read(notebookMetaProvider.notifier)
            .recordGeneration(
              platform,
              NotebookGenerationMeta(
                workspaceFolder: result.workspaceFolder,
                filename: result.notebookFilenames.first,
                generatedAt: result.generatedAt,
              ),
            );

        // Generated and openable in Jupyter, but there is no training loop to
        // run — executing it would fail in a way that looks like the user's
        // fault. Stop here; the notebook is still recorded above so "Open
        // notebook" works for this platform.
        if (!result.trainable) {
          setNotApplicableState(platform, result.notTrainableReason, attemptId);
          return;
        }
      }

      if (await hasExecutingManualSession(api, notebookPath)) {
        if (!ref
            .read(studioResultSessionProvider.notifier)
            .isCurrentAttempt(attemptId)) {
          return;
        }
        final proceed = await confirmStopManualSession();
        if (!ref
            .read(studioResultSessionProvider.notifier)
            .isCurrentAttempt(attemptId)) {
          return;
        }
        if (!proceed) {
          ref
              .read(studioResultSessionProvider.notifier)
              .markCancelled(platform);
          return;
        }
      }

      final jobId = await api.runNotebook(
        notebookPath: notebookPath,
        platform: platform,
      );

      if (!ref
          .read(studioResultSessionProvider.notifier)
          .isCurrentAttempt(attemptId)) {
        return;
      }
      ref
          .read(studioResultSessionProvider.notifier)
          .registerJob(platform, jobId);
      ref.read(trainingJobIdsProvider.notifier).setJobId(platform, jobId);
      subscribeToJob(platform, jobId, attemptId);
    } catch (e, s) {
      setErrorState(platform, e, s, attemptId);
    }
  }

  void subscribeToJob(String platform, String jobId, String attemptId) {
    final api = ref.read(apiClientProvider);
    final sub = api
        .streamTrainingEvents(jobId)
        .listen(
          (event) => onEvent(platform, event, attemptId),
          onError: (Object e, StackTrace s) {
            unawaited(
              handleStreamTransportLoss(
                platform,
                jobId,
                attemptId,
                transportError: e,
                transportStack: s,
              ),
            );
          },
          onDone: () {
            if (!ref
                .read(studioResultSessionProvider.notifier)
                .isCurrentAttempt(attemptId)) {
              return;
            }
            if (ref
                    .read(studioResultSessionProvider)
                    .platforms[platform]
                    ?.outcome ==
                StudioPlatformOutcome.running) {
              unawaited(handleStreamTransportLoss(platform, jobId, attemptId));
            }
          },
          cancelOnError: true,
        );
    _subscriptions[platform] = sub;
  }

  /// Re-subscribes to every platform still marked running — used when the app
  /// returns to the foreground after the OS tore down SSE sockets.
  void resyncRunningSubscriptions() {
    final session = ref.read(studioResultSessionProvider);
    final attemptId = session.attemptId;
    if (attemptId == null || !session.isAnyRunning) return;

    final jobIds = ref.read(trainingJobIdsProvider);
    for (final entry in session.platforms.entries) {
      if (entry.value.outcome != StudioPlatformOutcome.running) continue;
      final jobRef = jobIds[entry.key];
      if (jobRef == null) continue;
      _subscriptions[entry.key]?.cancel();
      subscribeToJob(entry.key, jobRef.jobId, attemptId);
    }
  }

  /// After an SSE transport drop, reconcile against the server job record
  /// before surfacing a run failure in the UI.
  Future<void> handleStreamTransportLoss(
    String platform,
    String jobId,
    String attemptId, {
    Object? transportError,
    StackTrace? transportStack,
  }) async {
    if (!ref
        .read(studioResultSessionProvider.notifier)
        .isCurrentAttempt(attemptId)) {
      return;
    }
    if (transportError != null &&
        !isRecoverableTrainingStreamError(transportError)) {
      setErrorState(platform, transportError, transportStack, attemptId);
      return;
    }

    final api = ref.read(apiClientProvider);
    try {
      final status = await api.getJobStatus(jobId);
      if (!ref
          .read(studioResultSessionProvider.notifier)
          .isCurrentAttempt(attemptId)) {
        return;
      }
      if (_isActiveJobStatus(status.status)) {
        _subscriptions[platform]?.cancel();
        subscribeToJob(platform, jobId, attemptId);
        return;
      }
      if (status.status == 'complete') {
        ref.read(studioResultSessionProvider.notifier).markComplete(platform);
        return;
      }
      if (status.status == 'failed') {
        setErrorState(
          platform,
          status.error ?? 'Training job failed',
          null,
          attemptId,
        );
        return;
      }
    } on Object catch (_) {
      // Fall through to the transport error below.
    }

    if (transportError != null) {
      setErrorState(platform, transportError, transportStack, attemptId);
      return;
    }
    setErrorState(
      platform,
      'Run ended without progress events.',
      null,
      attemptId,
    );
  }

  void onEvent(String platform, Map<String, dynamic> event, String attemptId) {
    if (!ref
        .read(studioResultSessionProvider.notifier)
        .isCurrentAttempt(attemptId)) {
      return;
    }
    final type = event['type'] as String? ?? '';
    if (type == 'epoch') {
      final epochEvent = TrainingEpochEvent.fromJson({
        'replayed': false,
        ...event,
      });
      final rates = epochEvent.layerSpikeRates;
      ref
          .read(studioResultSessionProvider.notifier)
          .recordEpoch(platform, epochEvent);

      // Drive canvas colour overlay — resolve backend rate keys to the
      // canvas node ids they describe before pushing into the provider.
      if (rates.isNotEmpty) {
        final nodes = ref.read(canvasProvider).graph.nodes;
        final mapped = matchSpikeRatesToNodeIds(rates, nodes);
        if (mapped.isNotEmpty) {
          ref.read(trainingModeProvider.notifier).setRates(mapped);
        }
      }
    } else if (type == 'done' || type == 'complete') {
      ref.read(studioResultSessionProvider.notifier).markComplete(platform);
    } else if (type == 'failed') {
      setErrorState(
        platform,
        event['error']?.toString() ?? 'Training job failed with no details.',
        null,
        attemptId,
      );
    }
  }

  /// Cancels every in-flight job-progress subscription without touching
  /// session state — used before starting a fresh attempt.
  void cancelSubscriptions() {
    for (final sub in _subscriptions.values) {
      sub.cancel();
    }
    _subscriptions.clear();
  }

  void stopTraining() {
    cancelSubscriptions();
    ref.read(studioResultSessionProvider.notifier).cancelRunning();
  }

  void setErrorState(
    String platform,
    Object e, [
    StackTrace? s,
    String? attemptId,
  ]) {
    if (attemptId != null &&
        !ref
            .read(studioResultSessionProvider.notifier)
            .isCurrentAttempt(attemptId)) {
      return;
    }
    late final String summary;
    late final String detail;
    if (e is ApiException) {
      summary = 'run failed - error ${e.statusCode}';
      final buf = StringBuffer();
      buf.writeln('HTTP ${e.statusCode}');
      buf.writeln();
      buf.writeln('Response body:');
      buf.writeln(e.body);
      if (s != null) {
        buf.writeln();
        buf.writeln('Stack trace:');
        buf.write(s.toString());
      }
      detail = buf.toString();
    } else if (e is DatasetPreparationException) {
      summary = 'run failed - dataset file unavailable';
      detail = e.message;
    } else {
      summary = 'run failed - unexpected error';
      detail = '$e${s != null ? '\n\nStack trace:\n$s' : ''}';
    }
    ref
        .read(studioResultSessionProvider.notifier)
        .markError(platform, summary: summary, detail: detail);
  }

  void setNotApplicableState(
    String platform,
    String reason, [
    String? attemptId,
  ]) {
    if (attemptId != null &&
        !ref
            .read(studioResultSessionProvider.notifier)
            .isCurrentAttempt(attemptId)) {
      return;
    }
    ref
        .read(studioResultSessionProvider.notifier)
        .markNotApplicable(platform, reason);
  }
}
