"""Initial migration.

Revision ID: a838fc1f0016
Revises:
Create Date: 2026-03-28 16:01:24.901170

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a838fc1f0016"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "activity_entries",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("timestamp", sa.String(), nullable=False),
        sa.Column("user", sa.String(), nullable=False),
        sa.Column("app", sa.String(), nullable=False),
        sa.Column("project_id", sa.String(), nullable=True),
        sa.Column("action", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("link", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_activity_entries_app"), "activity_entries", ["app"], unique=False)
    op.create_index(op.f("ix_activity_entries_id"), "activity_entries", ["id"], unique=False)
    op.create_index(
        op.f("ix_activity_entries_project_id"), "activity_entries", ["project_id"], unique=False
    )
    op.create_index(
        op.f("ix_activity_entries_timestamp"), "activity_entries", ["timestamp"], unique=False
    )
    op.create_table(
        "milestones",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("project_id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("target_date", sa.String(), nullable=True),
        sa.Column("completed_date", sa.String(), nullable=True),
        sa.Column("auto_detect", sa.JSON(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_milestones_id"), "milestones", ["id"], unique=False)
    op.create_index(op.f("ix_milestones_project_id"), "milestones", ["project_id"], unique=False)
    op.create_table(
        "notes",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("project_id", sa.String(), nullable=False),
        sa.Column("asset_id", sa.String(), nullable=True),
        sa.Column("author", sa.String(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("created_at", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_notes_asset_id"), "notes", ["asset_id"], unique=False)
    op.create_index(op.f("ix_notes_id"), "notes", ["id"], unique=False)
    op.create_index(op.f("ix_notes_project_id"), "notes", ["project_id"], unique=False)
    op.create_table(
        "projects",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("created_at", sa.String(), nullable=False),
        sa.Column("updated_at", sa.String(), nullable=False),
        sa.Column("owner", sa.String(), nullable=False),
        sa.Column("members", sa.JSON(), nullable=False),
        sa.Column("links", sa.JSON(), nullable=False),
        sa.Column("tags", sa.JSON(), nullable=False),
        sa.Column("milestones", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_projects_id"), "projects", ["id"], unique=False)
    op.create_index(op.f("ix_projects_name"), "projects", ["name"], unique=False)
    op.create_table(
        "shared_assets",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("author", sa.String(), nullable=False),
        sa.Column("tags", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.String(), nullable=False),
        sa.Column("file_path", sa.String(), nullable=False),
        sa.Column("file_size_bytes", sa.Integer(), nullable=False),
        sa.Column("metadata_", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_shared_assets_id"), "shared_assets", ["id"], unique=False)
    op.create_index(op.f("ix_shared_assets_name"), "shared_assets", ["name"], unique=False)
    op.create_index(op.f("ix_shared_assets_type"), "shared_assets", ["type"], unique=False)
    op.create_table(
        "suite_config",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("neurosim_url", sa.String(), nullable=False),
        sa.Column("neurochip_url", sa.String(), nullable=False),
        sa.Column("neurobench_url", sa.String(), nullable=False),
        sa.Column("neurosense_url", sa.String(), nullable=False),
        sa.Column("neurocnl_url", sa.String(), nullable=False),
        sa.Column("shared_storage_path", sa.String(), nullable=False),
        sa.Column("default_project_settings", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "workflow_runs",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("workflow_id", sa.String(), nullable=False),
        sa.Column("project_id", sa.String(), nullable=False),
        sa.Column("started_at", sa.String(), nullable=False),
        sa.Column("completed_at", sa.String(), nullable=True),
        sa.Column("heartbeat", sa.String(), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("steps", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_workflow_runs_id"), "workflow_runs", ["id"], unique=False)
    op.create_index(
        op.f("ix_workflow_runs_project_id"), "workflow_runs", ["project_id"], unique=False
    )
    op.create_index(
        op.f("ix_workflow_runs_workflow_id"), "workflow_runs", ["workflow_id"], unique=False
    )
    op.create_table(
        "workflow_templates",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("steps", sa.JSON(), nullable=False),
        sa.Column("builtin", sa.Boolean(), nullable=False),
        sa.Column("schedule", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_workflow_templates_id"), "workflow_templates", ["id"], unique=False)
    op.create_index(
        op.f("ix_workflow_templates_name"), "workflow_templates", ["name"], unique=False
    )

    op.create_table(
        "users",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("full_name", sa.String(), nullable=False),
        sa.Column("hashed_password", sa.String(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_admin", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")

    op.drop_index(op.f("ix_workflow_templates_name"), table_name="workflow_templates")
    op.drop_index(op.f("ix_workflow_templates_id"), table_name="workflow_templates")
    op.drop_table("workflow_templates")
    op.drop_index(op.f("ix_workflow_runs_workflow_id"), table_name="workflow_runs")
    op.drop_index(op.f("ix_workflow_runs_project_id"), table_name="workflow_runs")
    op.drop_index(op.f("ix_workflow_runs_id"), table_name="workflow_runs")
    op.drop_table("workflow_runs")
    op.drop_table("suite_config")
    op.drop_index(op.f("ix_shared_assets_type"), table_name="shared_assets")
    op.drop_index(op.f("ix_shared_assets_name"), table_name="shared_assets")
    op.drop_index(op.f("ix_shared_assets_id"), table_name="shared_assets")
    op.drop_table("shared_assets")
    op.drop_index(op.f("ix_projects_name"), table_name="projects")
    op.drop_index(op.f("ix_projects_id"), table_name="projects")
    op.drop_table("projects")
    op.drop_index(op.f("ix_notes_project_id"), table_name="notes")
    op.drop_index(op.f("ix_notes_id"), table_name="notes")
    op.drop_index(op.f("ix_notes_asset_id"), table_name="notes")
    op.drop_table("notes")
    op.drop_index(op.f("ix_milestones_project_id"), table_name="milestones")
    op.drop_index(op.f("ix_milestones_id"), table_name="milestones")
    op.drop_table("milestones")
    op.drop_index(op.f("ix_activity_entries_timestamp"), table_name="activity_entries")
    op.drop_index(op.f("ix_activity_entries_project_id"), table_name="activity_entries")
    op.drop_index(op.f("ix_activity_entries_id"), table_name="activity_entries")
    op.drop_index(op.f("ix_activity_entries_app"), table_name="activity_entries")
    op.drop_table("activity_entries")
    # ### end Alembic commands ###
